# Headers
Header set Access-Control-Allow-Origin https://*.infommo.es
Header set Access-Control-Allow-Origin https://*.laeradelosdioses.com
#Header set Access-Control-Allow-Origin https://www.google.com

# Da problemas con Adsense
#Header set Cross-Origin-Embedder-Policy: require-corp

#Header set Timing-Allow-Origin: https://*.infommo.es,https://*.laeradelosdioses.com
