<?php
$creaturefields = "(creatureid,creaturename,creaturelevel,creatureweapon,creaturelose,creaturewin,creaturegold,creatureexp,creaturehealth,creatureattack,creaturedefense,creatureaiscript,createdby,forest,graveyard,oldcreatureexp)";
$creaturefields111 = "(creatureid,creaturename,creaturelevel,creatureweapon,creaturelose,creaturewin,creaturegold,creatureexp,creaturehealth,creatureattack,creaturedefense,creatureaiscript,createdby,forest,graveyard)";
return array(
	'-1' => [], //needed just as a placeholder for new installs.
	'0.9' => include_once 'lib/installer/versions/0-9.php',
"0.9.1"=>array(
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6Just wait for my revenge, `4{badguy}`6. It will be swift!`5\" {goodguy} declares.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6I\\'m really going to enjoy this new `4{weapon}`6 that {goodguy}`6 had,`5\" exclaimed {badguy}.','joe')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6Aah, so `bthat\\'s`b what `4{creatureweapon}`6 is for!`5\" exclaimed {badguy}','joe')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6Oh man!  I didn\\'t think you had it in you, `5{badguy}`6,`5\" {goodguy} exclaims.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5{badguy} was overheard saying, \"`6{hisher} `4{weapon}`6 was no match for my `4{creatureweapon}`6!`5\"','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6You know, you really shouldn\\'t have a `4{weapon}`6 unless you know how to use it,`5\" suggested {badguy}.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6`bARRRGGGGGGG`b!!`5\" {goodguy} screams in frustration.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6How could I be so feeble?`5\" {goodguy} laments.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6I must not be as sturdy as I thought...!`5\" {goodguy} concedes.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6Watch your back, `4{badguy}`6, I am coming for you!`5\" {goodguy} warns.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6This both sucks and blows!`5\" wails {goodguy}.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6I see London, I see France, I see `4{goodguy}\\'s`6 underpants!`5\" reveals {badguy}.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6The Healer\\'s Hut can\\'t help you now, `4{goodguy}`6!`5\" chides {badguy}.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5{badguy} smiles.  \"`6You are too slow.  You are too weak.`5\"','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5{goodguy} bangs {hisher} head against a stone...\"`6Stupid, stupid, stupid!`5\" {heshe} was heard to say.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6My ego can\\'t take much more of this bruising!`5\" exclaims {goodguy}.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6Why didn\\'t I become a successful doctor like my father suggested?`5\" wonders {goodguy} aloud.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6Maybe `bnext`b time you won\\'t be so cocky!`5\" laughs {badguy}','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6A baby could wield a `4{weapon} `6better than that!`5\" {badguy} proclaims.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6You should have just stayed in bed,`5\" {badguy} suggests.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6Well isn\\'t that a kick in the crotch?!`5\" {goodguy} observes.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6Come back when you learn how to fight,`5\" {baguy} scoffs.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6Next time, eat your Wheaties,`5\" {badguy} suggests.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5 \"`6You are dishonorable, `4{badguy}`6!`5\" {goodguy} cries.','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`4{goodguy}`6, your lack of posture is a disgrace,`5\" {badguy}  states. ','Bluspring')",
"INSERT INTO " . db_prefix("taunts") . " VALUES (0,'`5\"`6You know, `4{goodguy}`6 really had it coming to {himher} after all those things `bI`b said about `b{hisher}`b mom`5,\" commented {badguy}.','Joe')",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Rake',48,1,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Trowel',225,2,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spade',585,3,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Adze',990,4,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Gardening Hoe',1575,5,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Torch',2250,6,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Pitchfork',2790,7,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Shovel',3420,8,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Hedge Trimmers',4230,9,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Hatchet',5040,10,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Carving Knife',5850,11,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Rusty Iron Wood-Chopping Axe',6840,12,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dull Steel Wood-chopping Axe',8010,13,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Sharp Steel Wood-chopping Axe',9000,14,0)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Woodsman\\'s Axe',10350,15,0)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Fuzzy Slippers',48,1,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Flannel Pajamas',225,2,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Homespun Longjohns',585,3,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Homespun Undershirt',990,4,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Knitted Socks',1575,5,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Knitted Gloves',2250,6,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Old Leather Boots',2790,7,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Homespun Pants',3420,8,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Homespun Tunic',4230,9,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Gypsy Cape',5040,10,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Old Leather Cap',5850,11,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Old Leather Bracers',6840,12,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Traveller\\'s Shield',8010,13,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Old Leather Pants',9000,14,0)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Old Leather Tunic',10350,15,0)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Pebbles',48,1,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Stones',225,2,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Rocks',585,3,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Small Treebranch',990,4,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Large Treebranch',1575,5,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Thickly Padded Sparring Pole',2250,6,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Thinly Padded Sparring Pole',2790,7,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Wooden Stave',3420,8,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Wooden Practice Sword',4230,9,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Blunt Bronze Short Sword',5040,10,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Crafted Bronze Short Sword',5850,11,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Rusty Steel Short Sword',6840,12,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dull Steel Short Sword',8010,13,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Sharp Steel Short Sword',9000,14,1)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Pages\\'s Short Sword',10350,15,1)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Flip-Flops',48,1,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Swimsuit and Towel',225,2,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Cotton Undershirt',585,3,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wool Socks',990,4,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wool Gloves',1575,5,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Leather Boots',2250,6,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Leather Cap',2790,7,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Leather Bracers',3420,8,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Leather Leggings',4230,9,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Leather Tunic',5040,10,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Hooded Leather Cape',5850,11,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Deerskin Leggings',6840,12,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Deerskin Belt',8010,13,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Deerskin Tunic',9000,14,1)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Small Rawhide Shield',10350,15,1)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dull Bronze Sword',48,1,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Bronze Sword',225,2,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Crafted Bronze Sword',585,3,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dull Iron Sword',990,4,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Iron Sword',1575,5,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Enchanted Sword',9000,14,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Crafted Iron Sword',2250,6,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Rusty Steel Sword',2790,7,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dull Steel Sword',3420,8,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Crafted Steel Sword',4230,9,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Engraved Steel Sword',5040,10,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Steel Sword with Jeweled Hilt',5850,11,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Golden Hilted Sword',6840,12,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Platinum Hilted Sword',8010,13,2)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Adept\\'s Sword',10350,15,2)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Workboots',48,1,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Overalls',225,2,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Sturdy Leather Gloves',585,3,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Sturdy Leather Bracers',990,4,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Sturdy Leather Boots',1575,5,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Sturdy Leather Helm',2250,6,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Sturdy Leather Pants',2790,7,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Sturdy Leather Tunic',3420,8,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Sturdy Leather Cloak',4230,9,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Woodsman\\'s Helm',5040,10,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Woodsman\\'s Gauntlets',5850,11,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Woodsman\\'s Bracers',6840,12,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Woodsman\\'s Greaves',8010,13,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Woodsman\\'s Tunic',9000,14,2)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Woodsman\\'s Kite Shield',10350,15,2)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Steel Longsword',48,1,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Etched Steel Longsword',585,3,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Polished Steel Longsword',225,2,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Balanced Steel Longsword',990,4,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Perfectly Balanced Steel Longsword',1575,5,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Engraved Steel Longsword',2250,6,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Longsword with Silver-plated Hilt',2790,7,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Longsword with Gold-plated Hilt',3420,8,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Longsword with Solid Gold Hilt',4230,9,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Longsword with Solid Platinum Hilt',5040,10,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Moonsilver Longsword',5850,11,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Autumngold Longsword',6840,12,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Elfsilver Longsword',8010,13,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Enchanted Longsword',9000,14,3)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Wolfmaster\\'s Longsword',10350,15,3)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Showercap and Towel',48,1,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Bathrobe',225,2,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfskin Gloves',585,3,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfskin-lined Boots',990,4,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfskin Bracers',1575,5,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfskin Pants',2250,6,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfskin Tunic',2790,7,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Hooded Wolfskin Cape',3420,8,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfmaster\\'s Bracers',4230,9,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfmaster\\'s Gauntlets',5040,10,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfmasters Helm',5850,11,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfmaster\\'s Leggings',6840,12,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfmaster\\'s Belted Jerkin',8010,13,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Wolfhide Cape',9000,14,3)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Shield of the Wolf Master',10350,15,3)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Poorly Balanced Bastard Sword',48,1,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Tarnished Bastard Sword',225,2,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Iron Bastard Sword',585,3,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Steel Bastard Sword',990,4,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Balanced Steel Bastard Sword',1575,5,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Perfectly Balanced Bastard Sword',2250,6,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Rune-etched Bastard Sword',2790,7,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Bronze-inlay Bastard Sword',3420,8,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Silver-inlay Bastard Sword',4230,9,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Gold-inlay Bastard Sword',5040,10,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Nightsilver Bastard Sword',5850,11,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Morning-gold Bastard Sword',6840,12,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Truesplendor Bastard Sword',8010,13,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Enchanted Elfgold Bastard Sword',9000,14,4)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Noble\\'s Bastard Sword',10350,15,4)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Sweat Pants',48,1,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Sweat Shirt',225,2,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Studded Leather Helm',585,3,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Studded Leather Gauntlets',990,4,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Hardened Leather Boots',1575,5,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Studded Leather Leggings',2250,6,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Studded Leather Tunic',2790,7,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Tanner\\'s Cape',3420,8,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Rusty Chainmail Helm',4230,9,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Rusty Chainmail Gauntlets',5040,10,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Rusty Chainmail Bracers',5850,11,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Rusty Chainmail Boots',6840,12,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Rusty Chainmail Greaves',8010,13,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Rusty Chainmail Tunic',9000,14,4)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Large Iron Buckler',10350,15,4)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Tarnished Iron Claymore',48,1,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Polished Iron Claymore',225,2,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Rusty Steel Claymore',585,3,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Steel Claymore',990,4,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Finely Crafted Steel Claymore',1575,5,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Scottish Broadsword',2250,6,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Viking War Sword',2790,7,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Barbarian\\'s Sword',3420,8,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Scottish Basket-Hilt Claymore',4230,9,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Agincourt Steel Sword',5040,10,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Celtic Combat Sword',5850,11,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Norseman\\'s Sword',6840,12,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Knight\\'s Sword',8010,13,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Heraldic Lion Claymore',9000,14,5)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dragon Soldier\\'s Claymore',10350,15,5)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Bunny Slippers',48,1,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Feety Pajamas',225,2,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Comfortable Leather Undergarments',585,3,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Heavy Chainmail Helm',990,4,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Heavy Chainmail Gauntlets',1575,5,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Heavy Chainmail Bracers',2250,6,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Heavy Chainmail Boots',2790,7,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Heavy Chainmail Greaves',3420,8,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Heavy Chainmail Tunic',4230,9,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Soldier\\'s Bracers',5040,10,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Soldier\\'s Gauntlets',5850,11,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Soldier\\'s Boots',6840,12,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Soldier\\'s Greaves',8010,13,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Soldier\\'s Chestplate',9000,14,5)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Soldier\\'s Shield',10350,15,5)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Two Broken Short Swords',48,1,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Two Short Swords',225,2,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Iron Scimitars',585,3,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Balanced Scimitars',990,4,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Tarnished Steel Scimitars',1575,5,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Rusty Steel Scimitars',2250,6,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Steel Scimitars',2790,7,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Bronze Hilted Steel Scimitars',3420,8,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Gold Hilted Steel Scimitars',4230,9,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Platinum Hilted Steel Scimitars',5040,10,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Crafted Adamantite Scimitars',5850,11,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Perfectly Crafted Adamantite Scimitars',6840,12,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Enchanted Scimitars',8010,13,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Drow Crafted Scimitars',9000,14,6)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Unicorn Blood-Forged Scimitars',10350,15,6)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Bluejeans',48,1,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Flannel Shirt',225,2,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Well Crafted Bronze Helm',585,3,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Well Crafted Bronze Gauntlets',990,4,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Well Crafted Bronze Bracers',1575,5,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Well Crafted Bronze Boots',2250,6,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Well Crafted Bronze Greaves',2790,7,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Well Crafted Bronze Chestplate',3420,8,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Bronze Helm',4230,9,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Bronze Gauntlets',5040,10,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Bronze Bracers',5850,11,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Bronze Boots',6840,12,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Bronze Greaves',8010,13,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Bronze Chestplate',9000,14,6)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Hooded Unicorn Skin Cloak',10350,15,6)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Chipped Iron Axe',48,1,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Iron Axe',225,2,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Rusty Steel Axe',585,3,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Fine Steel Axe',990,4,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Lumberjack\\'s Axe',1575,5,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Low Quality Battle Axe',2250,6,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Medium Quality Battle Axe',2790,7,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'High Quality Battle Axe',3420,8,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Double Bladed Axe',4230,9,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Double Bladed Battle Axe',5040,10,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Gold Plated Battle Axe',5850,11,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Platinum Hilted Battle Axe',6840,12,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Enchanted Battle Axe',8010,13,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dwarf Smith\\'s Battle Axe',9000,14,7)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dwarf Warrior\\'s Battle Axe',10350,15,7)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Barrel',48,1,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Lampshade',225,2,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Perfectly Crafted Steel Helm',585,3,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Perfectly Crafted Steel Gauntlets',990,4,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Perfectly Crafted Steel Boots',1575,5,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Perfectly Crafted Steel Bracers',2250,6,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Perfectly Crafted Steel Greaves',2790,7,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Perfectly Crafted Steel Chestplate',3420,8,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Griffon-Feather Cloak',4230,9,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dwarven Chainmail Helm',5040,10,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dwarven Chainmail Gauntlets',5850,11,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dwarven Chainmail Boots',6840,12,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dwarven Chainmail Bracers',8010,13,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dwarven Chainmail Greaves',9000,14,7)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dwarven Chainmail Chestplate',10350,15,7)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Broken Iron Mace',48,1,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Tarnished Iron Mace',225,2,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Polished Iron Mace',585,3,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Crafted Iron Mace',990,4,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Polished Steel Mace',1575,5,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Crafted Steel Mace',2250,6,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Poorly Balanced Double Mace',2790,7,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Well Balanced Double Mace',3420,8,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Battle Mace',4230,9,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'War Chieftain\\'s Battle Mace',5040,10,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'War Chieftain\\'s Morning Star',5850,11,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Adamantite Morning Star',6840,12,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dwarf Crafted Morning Star',8010,13,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Dwarf Warlord\\'s Morning Star',9000,14,8)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Enchanted Morning Star',10350,15,8)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Fig Leaf',48,1,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Kilt',225,2,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Majestic Gold Helm',585,3,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Majestic Gold Gauntlets',990,4,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Majestic Gold Boots',1575,5,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Bracers',2250,6,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Majestic Gold Greaves',2790,7,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Majestic Gold Chestplate',3420,8,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Majestic Gold Shield',4230,9,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Gold-Threaded Cloak',5040,10,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Ruby Ring',5850,11,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Sapphire Ring',6840,12,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Jade Ring',8010,13,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Amethyst Ring',9000,14,8)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Enchanted Diamond Ring',10350,15,8)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Boot Knife',48,1,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Target Knife',225,2,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Blackjack',585,3,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Throwing Star',990,4,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Hira-Shuriken',1575,5,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Throwing Spike',2250,6,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Atlatl',2790,7,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Qilamitautit Bolo',3420,8,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'War Quoait',4230,9,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Cha Kran',5040,10,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Fei Piau',5850,11,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Jen Piau',6840,12,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Gau dim Piau',8010,13,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Enchanted Throwing Axe',9000,14,9)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Teksolo\\'s Ninja Stars',10350,15,9)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Button',48,1,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Elven Silk Nightclothes',225,2,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Elven Silk Gloves',585,3,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Elven Silk Slippers',990,4,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Elven Silk Wristband',1575,5,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Leggings',2250,6,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Elven Silk Tunic',2790,7,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Elven Silk Cloak',3420,8,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Ring of Night',4230,9,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Ring of Day',5040,10,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Ring of Solitude',5850,11,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Ring of Peace',6840,12,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Ring of Courage',8010,13,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Ring of Virtue',9000,14,9)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Ring of Life',10350,15,9)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Farmer\\'s Bow & Wooden Arrows',48,1,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Farmer\\'s Bow & Stone Tipped Arrows',225,2,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Farmer\\'s Bow & Steel Tipped Arrows',585,3,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Hunter\\'s Bow & Wooden Arrows',990,4,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Hunter\\'s Bow & Stone Tipped Arrows',1575,5,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Hunter\\'s Bow & Steel Tipped Arrows',2250,6,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Ranger\\'s Bow & Wooden Arrows',2790,7,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Ranger\\'s Bow & Stone Tipped Arrows',3420,8,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Ranger\\'s Bow & Steel Tipped Arrows',4230,9,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Longbow',5040,10,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Crossbow',5850,11,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Elvish Longbow',6840,12,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Elvish Longbow & Flame Tipped Arrows',8010,13,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Elvish Longbow & Enchanted Arrows',9000,14,10)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Longbow of the Elf King',10350,15,10)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Hooded Cloak',5040,10,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Chestplate',4230,9,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Greaves',3420,8,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Boots',2790,7,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Gorget',2250,6,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Bracers',1575,5,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Gauntlets',990,4,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Helm',585,3,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Platform Shoes',225,2,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Leisure Suit',48,1,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus Feather Pendant',5850,11,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus Feather Belt',6840,12,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Emblazoned Shield',8010,13,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Emblazoned Ring',9000,14,10)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pegasus\\' Emblazoned Crown',10350,15,10)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Long Sword',225,2,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Short Sword',48,1,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Bastard Sword',585,3,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Scimitars',990,4,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Battle Axe',1575,5,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Throwing Hammer',2250,6,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Morning Star',2790,7,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Compound Bow',3420,8,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Rapier',4230,9,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Sabre',5040,10,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Light Sabre',5850,11,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Wakizashi',6840,12,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s 2-Handed War Sword',8010,13,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s 2-handed War Axe',9000,14,11)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'MightyE\\'s Claymore',10350,15,11)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'New Clothes',48,1,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Chicken Suit',225,2,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Gauntlets of Grace',585,3,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Bracer of Beauty',990,4,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Helm of Health',1575,5,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Greaves of Good Fortune',2250,6,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Boots of Bravery',2790,7,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Tunic of Tolerance',3420,8,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Cloak of Confidence',4230,9,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Ring of Righteousness',5040,10,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Necklace of Narcissism',5850,11,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Pendant of Power',6840,12,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Breastplate of Benevolence',8010,13,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Shield of Superiority',9000,14,11)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Scepter of Strength',10350,15,11)",

"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Fire',48,1,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Earthquake',225,2,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Flood',585,3,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Hurricane',990,4,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Mind Control',1575,5,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Lightning',2250,6,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Weakness',2790,7,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Fear',3420,8,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Poison',4230,9,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Spirit Possession',5040,10,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Despair',5850,11,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Bat Summoning',6840,12,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Wolf Summoning',8010,13,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Unicorn Summoning',9000,14,12)",
"INSERT INTO " . db_prefix("weapons") . " VALUES (0,'Spell of Dragon Summoning',10350,15,12)",

"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Skin Leather Helm',48,1,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Skin Leather Gauntlets',225,2,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Skin Leather Boots',585,3,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Skin Leather Bracers',990,4,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Skin Leather Leggings',1575,5,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Skin Leather Tunic',2250,6,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Skin Leather Cloak',2790,7,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Scale Helm',3420,8,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Scale Gauntlets',4230,9,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Scale Boots',5040,10,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Scale Bracers',5850,11,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Scale Greaves',6840,12,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Scale Chestplate',8010,13,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Scale Cloak',9000,14,12)",
"INSERT INTO " . db_prefix("armor") . " VALUES (0,'Dragon Talon Shield',10350,15,12)",
),
"0.9.2"=>array(
),
"0.9.3"=>array(),
"0.9.4"=>array(),
"0.9.5"=>array(),
"0.9.6"=>array(
),
"0.9.7"=>array(
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (220, 'Frenzied vampire bats', 15, 'Numerous attacks', 'Why are there so many darn bats in this forest?', NULL, 531, 189, 155, 29, 21, NULL, 'Appleshiner', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (221, 'Vampirus,the Bat God', 16, 'Godly Power', 'You are even more god-like then he!', '', 563, 207, 166, 31, 22, '', 'Appleshiner', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (222, 'Old Man Winter', 9, 'Bitter Cold', 'You shake your fist over his dead, pathetic corpse.', NULL, 336, 101, 94, 17, 13, NULL, NULL, 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (223, 'Deranged Gnome', 1, 'A Cloth Draped Mirror', 'What happens when I do THIS?', NULL, 36, 14, 10, 1, 1, NULL, NULL, 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (224, 'Water Sprite', 1, 'Burst of Water', 'That was refreshing.', NULL, 36, 14, 10, 1, 1, NULL, NULL, 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (225, 'Water Nymph', 3, 'A torrent of water', 'I didn''t need a bath, thank you.', NULL, 148, 34, 32, 5, 4, NULL, NULL, 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (226, 'Lady of the Lake', 10, 'Excalibur', 'Take that, you watery tart!', NULL, 369, 114, 105, 19, 14, NULL, NULL, 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (227, 'Cunning Sapling', 1, 'Arrrr!', 'Ah Ha! A toothpick!', NULL, 36, 14, 10, 1, 1, NULL, NULL, 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (228, 'Pirate Tree', 5, 'A loud ARRRRR!', 'Arrrrrr! indeed.', NULL, 198, 55, 53, 9, 7, NULL, NULL, 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (229, 'Undead Centurion', 5, 'Bronze Spear', 'Hmm Not too good at combat the second time around, either.', NULL, 198, 55, 53, 9, 7, NULL, NULL, 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (230, 'Insane Bard', 2, 'Iambic Pentameter', 'Slings and Arrows of outrageous fortune? Nope.  Just the can o'' Whoopass.', NULL, 97, 24, 21, 3, 3, NULL, NULL, 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (231, 'Twig Man', 1, 'Brambles and Briars', 'I snapped him like a.. well, twig.', NULL, 36, 14, 10, 1, 1, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (232, 'Rabid Mouse', 1, 'Little Bitty Teeth', 'Those little teeth HURT!', NULL, 36, 14, 10, 1, 1, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (233, 'Stray Cat', 1, 'A Midnight Serenade', 'Finally! Peace in the night!', NULL, 36, 14, 10, 1, 1, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (234, 'Big Hairy Spider', 1, 'Sticky stringy webs', 'I *HATE* spiders!', NULL, 36, 14, 10, 1, 1, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (235, 'Goblin Lackey', 1, 'Dull Knife', 'Who knew goblins had lackeys?', NULL, 36, 14, 10, 1, 1, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (236, 'Crazy Chihuahua', 1, 'Fast food cravings', 'Here taco, taco, taco.', '', 36, 14, 10, 1, 1, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (237, 'Looney Rabbit', 1, 'Wisecracks', 'Th- Th- That''s all folks!', NULL, 36, 14, 10, 1, 1, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (238, 'Undead Oarsman', 1, 'Rotten Oar', 'Funny... I didn''t see any water around here.', '', 36, 14, 10, 1, 1, '', 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (239, 'Lost Ghostling', 2, 'Sad Weeping', 'Well, I''m sure that helped him on his way...', '', 97, 24, 21, 3, 3, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (240, 'Angry Titmouse', 2, 'Incessant Chattering', 'You swat the little bird out of the air with little effort.', '', 97, 24, 21, 3, 3, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (241, 'Fabianist Youth Member', 2, 'Marxist Doctrine', 'Socialize THAT.', NULL, 97, 24, 21, 3, 3, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (242, 'Little Bogeyman', 2, 'Noises in the Dark', 'Hmm, not so scary when you have grown up...', '', 97, 24, 21, 3, 3, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (243, 'Big Bogeyman', 3, 'Fingers poking you as you sleep.', 'Ok... that was weird.  But not scary... Nope not at all... I think I''ll leave the light on at the inn tonight though.', '', 148, 34, 32, 5, 4, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (244, 'Coblynau', 2, 'Ill tempered tricks', 'Maybe I better leave him part of my lunch next time.', '', 97, 24, 21, 3, 3, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (245, 'Jack O''Lantern', 2, 'Eternal Wandering', 'The light has gone out of his life.', NULL, 97, 24, 21, 3, 3, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (246, 'Fresh Ghoul', 2, 'Long Pointed Nails', 'You leave him to the mercies of the other ghouls.', '', 97, 24, 21, 3, 3, '', 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (247, 'Dry Skeleton', 2, 'a Rusty Dagger', 'The skeleton crumbles into a pile of dust.', NULL, 97, 24, 21, 3, 3, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (248, 'Newly Dead Zombie', 2, 'Fists', 'Maybe now it can rest in peace.', NULL, 97, 24, 21, 3, 3, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (249, 'Faerie hound', 2, 'Glowing Eyes', 'The embers in the eye sockets dim and sputter out.', NULL, 97, 24, 21, 3, 3, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (250, 'Apprentice Necromancer', 3, 'Life Draining Spells', 'He gasps a final breath and melts into a tarry liquid.', NULL, 148, 34, 32, 5, 4, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (251, 'Doppleganger', 3, 'Shape changing', 'You kill the doppleganger and he returns to his true form.', NULL, 148, 34, 32, 5, 4, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (252, 'Forest Thief', 3, 'Poisoned Short Sword', 'His pockets were almost empty. I guess he wasn''t much of a thief.', '', 148, 34, 32, 5, 4, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (253, 'Mouldy Skeleton', 3, 'Rotten Fists', 'Heeeeey, didn''t you see him in town last week?', NULL, 148, 34, 32, 5, 4, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (254, 'Angry Fairy', 3, 'Furious Fairy Dust', 'He disappears in a cloud of fairy dust.', NULL, 148, 34, 32, 5, 4, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (255, 'Goblin Hunter', 3, 'a Shortbow', 'Only one? Don''t they usually travel in packs?', NULL, 148, 34, 32, 5, 4, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (256, 'Bobcat Cub', 3, 'Sharp Claws', 'Even the cute fuzzy kittens are evil in this place.', NULL, 148, 34, 32, 5, 4, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (257, 'Animate Junkheap', 3, 'Stench of 1000 rotten potatoes', 'Just call you the De-Animator!', NULL, 148, 34, 32, 5, 4, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (258, 'Necromancer', 4, 'Strength Draining Touch', 'In a cloud of black smoke, his body wafts away on the breeze.', '', 162, 45, 43, 7, 6, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (259, 'Reed Golem', 4, 'Fists of Thorns', 'The only thing left was a tiny bale of hay.', NULL, 162, 45, 43, 7, 6, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (260, 'Goblin Shaman', 4, 'Primitive Magic', '\"Oooga Booga,\" indeed.', NULL, 162, 45, 43, 7, 6, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (261, 'Steam Spirit', 4, 'Scalding Steam', 'Not so hot now, eh?', NULL, 162, 45, 43, 7, 6, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (262, 'Restless Zombie', 4, 'Broken Longsword', 'Finally he is at peace.', NULL, 162, 45, 43, 7, 6, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (263, 'Zombie Soldier', 4, 'Rusted Spear', 'His final orders were to march to hell.', '', 162, 45, 43, 7, 6, '', 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (264, 'Dark Imp', 4, 'Nagging Doubts', 'The imp implodes in a ball of flame.', NULL, 162, 45, 43, 7, 6, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (265, 'Giant Spider', 4, 'Fangs that glisten with poison', 'I really, really hate spiders.', '', 162, 45, 43, 7, 6, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (266, 'Undead Kitten', 4, 'Mews of Doom', 'Another evil cat sent to hell C.O.D.', NULL, 162, 45, 43, 7, 6, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (267, 'Flying Dagger', 4, 'Sharpened Steel Point', 'The dagger shatters when it hits the ground.', NULL, 162, 45, 43, 7, 6, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (268, 'Goblin Warrior', 5, 'Bent Short Sword', 'Gone... and forgotten.', '', 198, 55, 53, 9, 7, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (269, 'Experienced Necromancer', 5, 'a small group of Zombies', 'The necromancer turns into a pile of black sand and blows away.', NULL, 198, 55, 53, 9, 7, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (270, 'Flame Sprite', 5, 'Searing Flame', 'You cooled him off in a hurry...', NULL, 198, 55, 53, 9, 7, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (271, 'Mud Man', 5, 'Enchanted Mud', 'Defeated, the Mud Man dries up in the warm sun.', NULL, 198, 55, 53, 9, 7, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (272, 'Lupe the Hypnotic Chihuahua', 5, 'The stare of doom', 'You manage to break free of those deep hypnotic eyes...', NULL, 198, 55, 53, 9, 7, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (273, 'Ghoul', 5, 'Hunger for Flesh', 'The ghoul falls to the ground, a bit of flesh between his teeth.', NULL, 198, 55, 53, 9, 7, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (274, 'Seedy Cutthroat', 5, 'Sharpened Daggers', 'One more bandit removed from this forest.', NULL, 198, 55, 53, 9, 7, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (275, 'Ogre', 5, 'Broken treebranch', 'Boy, thats a face not even a mother could love.', NULL, 198, 55, 53, 9, 7, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (276, 'Crazy Woodsman', 5, 'Dull axe', 'Chopped him down to size...', NULL, 198, 55, 53, 9, 7, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (277, 'Flying Drakeling', 5, 'a Lashing Tail', 'You swat the small, majestic beast out of the air.', NULL, 198, 55, 53, 9, 7, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (278, 'Forest Cat', 6, 'Menacing Claws', 'Here kitty, kitty, kitty.', '', 234, 66, 64, 11, 8, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (279, 'Journeyman Necromancer', 6, 'An Undead Giant', 'The necromancer drifts away on a cloud of black smoke.', '', 234, 66, 64, 11, 8, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (280, 'Frigid Skeleton', 6, 'The Cold of the Grave', 'I''ll bet one of these guys could cool ale at the inn.', '', 234, 66, 64, 11, 8, '', 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (281, 'Frost Spirit', 6, 'Bone Chilling Cold', 'Puttin down another cold one.', '', 234, 66, 64, 11, 8, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (282, 'Dragon Slayer''s ghost', 6, 'Warnings of Doom', 'Everybody wondered what happened to him.', NULL, 234, 66, 64, 11, 8, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (283, 'Ettin Mage', 6, 'Double threat spells', 'Two heads are not better than one in this case.  Just more to lop off.', '', 234, 66, 64, 11, 8, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (284, 'Insane Brownie', 6, 'Faerie spells', 'This one''s nuts!', NULL, 234, 66, 64, 11, 8, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (285, 'Ghostly Wolfpack', 6, 'Ghostly Howls', 'Quiet settles in around you.  Finally.', NULL, 234, 66, 64, 11, 8, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (286, 'Wood Golem', 6, 'Oaken Fists', 'The truth gave you life and the truth set you free.', '', 234, 66, 64, 11, 8, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (287, 'Diseased Ent', 6, 'Twisted Branches', 'There must be fifty ways to cut your lumber. (Groan)', '', 234, 66, 64, 11, 8, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (288, 'Dark Druid', 7, 'Corrupted Nature', 'He lost me at the corrupt it to save it part.', NULL, 268, 77, 74, 13, 10, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (289, 'Lizard Man Scout', 7, 'Marginal Archery', 'I know where I can get him made into a nice pair of boots.', '', 268, 77, 74, 13, 10, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (290, 'Diabolic Footman', 7, 'A Demon Forged Mace', 'His armor sizzles and he melts as he crumples to the ground.', NULL, 268, 77, 74, 13, 10, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (291, 'Gargantuan Tree Spider', 7, 'Projectile Webbing', 'After you lop him in half, you realize he''s not so big.', NULL, 268, 77, 74, 13, 10, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (292, 'Flaming Zombie', 7, 'Fists covered in Flame', 'You extinguish the flame of life and the zombie falls to the ground, smoking.', NULL, 268, 77, 74, 13, 10, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (293, 'Eldritch Wizard', 7, 'Spells of Darkness', 'You slice him in two only to watch his body disappear, leaving an empty robe behind.', NULL, 268, 77, 74, 13, 10, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (294, 'Master Necromancer', 7, 'An Army of the Dead', 'You kill the necromancer and his minions disintegrate before your eyes.', NULL, 268, 77, 74, 13, 10, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (295, 'Animate Darkness', 7, 'The Darkness of a Thousand Nights', 'Light Slowly returns to this part of the forest.', '', 268, 77, 74, 13, 10, '', 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (296, 'Temple Guardian Statue', 7, 'Marble Fists', 'So, where''s the temple?', NULL, 268, 77, 74, 13, 10, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (297, 'Owlbear', 7, 'Claws and a bearhug', 'I don''t even want to know how they breed these.', '', 268, 77, 74, 13, 10, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (298, 'The Man In Black', 8, 'Necromantic Spells', 'Finally, I got my chance to kill him.', '', 302, 89, 84, 15, 11, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (299, 'Gnome Illusionist', 8, 'Fearsome Illusions', 'It was all in his head.', '', 302, 89, 84, 15, 11, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (300, 'Demon Skeleton', 8, 'Diabolic Runes', 'The spirits of its victims drag the skeleton back to hell.', '', 302, 89, 84, 15, 11, '', 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (301, 'Insane Master Druid', 8, 'The land Itself', 'His evil laughter dies with him.', NULL, 302, 89, 84, 15, 11, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (302, 'Water Elementalist', 8, 'Water Based Spells', 'He''s all wet.', NULL, 302, 89, 84, 15, 11, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (303, 'Earth Elementalist', 8, 'Earth Based Spells', 'He fought kind of Dirty.', '', 302, 89, 84, 15, 11, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (304, 'Ettin Warrior', 8, 'Two Clubs of Iron', 'They did all right until they hit each other.', NULL, 302, 89, 84, 15, 11, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (305, 'Forest Giant', 8, 'An Uprooted Tree', 'Ho, Ho, Ho that, green man.', NULL, 302, 89, 84, 15, 11, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (306, 'Demoniac Knight', 8, 'A Diabolic Lance', 'Good night, Sir Knight.', '', 302, 89, 84, 15, 11, '', 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (307, 'Giant Zombie', 8, 'Gigantic Fists', 'They DO smell worse when they are bigger!', NULL, 302, 89, 84, 15, 11, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (308, 'Frost Spectre', 9, 'The Chill Touch of the Grave', 'As you recover from the fight, the Spectre melts away into the shadows.', NULL, 336, 101, 94, 17, 13, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (309, 'Small Forest Dragon', 9, 'Snapping Jaws', 'Dragon? Check. Green? Check.  Huge? Nope.', '', 336, 101, 94, 17, 13, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (310, 'A Pack of Carnivorous Lemurs', 9, 'Hoots and Howls', 'What the heck is a Lemur??', NULL, 336, 101, 94, 17, 13, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (311, 'Albino Crypt Bear', 9, 'Foul Stench and Claws', 'You dispatch the bear and wonder if there are more lurking about.', NULL, 336, 101, 94, 17, 13, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (312, 'Black Knight of The Vale', 9, 'Ebony Sword', 'As he dies, he curses you and tells you that you will never defeat the dragon.', NULL, 336, 101, 94, 17, 13, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (313, 'Elmearian Spy', 9, 'Small Dagger', 'He eats his information before he dies, so you learn nothing from him.', NULL, 336, 101, 94, 17, 13, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (314, 'Stalking Shadow', 9, 'Fingers of Darkness', 'You send the ceature back to where it came from.', NULL, 336, 101, 94, 17, 13, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (315, 'Necromantic Archmagus', 9, 'Screams of a Thousand Souls', 'With his dying breath he explodes into a pillar of black flame!', NULL, 336, 101, 94, 17, 13, NULL, 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (316, 'Iron Golem', 9, 'Rusted Fists', 'The golem seizes up and you push him over.', '', 336, 101, 94, 17, 13, '', 'Hank', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (317, 'A Hell Hound', 9, 'Fiery Breath', 'He bursts into flames and is sucked into the earth.', NULL, 336, 101, 94, 17, 13, NULL, 'Hank', 1, 1, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (318, 'Corporate Lackey', 7, 'Buzzwords', 'Well, you sure reprioritized his downsizing.', NULL, 268, 77, 74, 13, 10, NULL, 'Moonchilde', 1, 0, NULL)",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields VALUES (319, 'SCO Lawyer', 8, 'Court Papers', 'There''s one lawyer who''ll never trouble you again!', NULL, 302, 89, 84, 15, 11, NULL, 'Moonchilde', 1, 1, NULL)",
'INSERT INTO ' . db_prefix("nastywords") . ' VALUES ("*damn* *dyke *fuck* *nigger* *phuck* *shit* amcik andskota arschloch arse* ass asshole atouche ayir bastard bitch* boiolas bollock* buceta butt* butt-pirate cabron cawk cazzo chink chraa chuj cipa clit cock* cum cunt* dago daygo dego dick* dike dildo dirsa dupa dziwka ejaculate ejackulate ekrem* ekto enculer faen fag* fanculo fanny fatass fcuk feces feg felcher ficken fitta fitte flikker foreskin phuck fuk* fut futkretzn fuxor gay gook guiena hell helvete hoer* honkey honky hor hore huevon hui injun jism jizz kanker* kawk kike klootzak knulle kraut kuk kuksuger kurac kurwa kusi* kyrp�* leitch lesbian lesbo mamhoon masturbat* merd merde mibun monkleigh mouliewop muie mulkku muschi nazis nepesaurio nigga* nigger nutsack orospu paska* pendejo penis perse phuck picka pierdol* pillu* pimmel pimpis piss* pizda poontsee poop porn preteen preud prick pron pula pule pusse pussy puta puto qahbeh queef* queer* qweef rautenberg schaffer scheiss* scheisse schlampe schmuck screw scrotum sharmuta sharmute shemale shipal shiz skribz skurwysyn slut smut sphencter shpincter spic spierdalaj splooge suka teets teez testicle tits titties titty twat twaty vittu votze wank* wetback* whoar whore wichser woose wop yed zabourah", "nasty")',
"INSERT INTO " . db_prefix("mounts") . " VALUES (1, 'Pony', 'This docile beast is young yet.', 'Horses', 'a:5:{s:4:\"name\";s:13:\"`&Pony Attack\";s:8:\"roundmsg\";s:26:\"Your pony fights with you!\";s:6:\"rounds\";s:2:\"20\";s:6:\"atkmod\";s:3:\"1.2\";s:8:\"activate\";s:7:\"offense\";}', 6, 0, 1, 1, 'You strap your {weapon} to your pony\\'s saddle bags, and head out for some adventure!', '`&Remembering that is has been quite some time since you last fed your pony, you decide this is a perfect time to relax and allow it to graze the field a bit. You doze off enjoying this peaceful serenity.`0', '`&You dismount in the field to allow your pony to graze for a moment even though it has recently been fully fed.  As you lean back in the grass to watch the clouds, your pony whickers softly and trots off into the underbrush.  You search for a while before returning to the fields hoping that it\\'ll return.  A short time later, your pony trots back into the clearing holding its head high, looking much more energized and with a very equine grin on its face.`0', 20, 'all', 0)",
"INSERT INTO " . db_prefix("mounts") . " VALUES (2, 'Gelding', 'This powerful beast is fiercely loyal.', 'Horses', 'a:5:{s:4:\"name\";s:16:\"`&Gelding Attack\";s:8:\"roundmsg\";s:29:\"Your gelding fights with you!\";s:6:\"rounds\";s:2:\"40\";s:6:\"atkmod\";s:3:\"1.2\";s:8:\"activate\";s:7:\"offense\";}', 10, 0, 1, 2, 'You strap your {weapon} to your gelding\\'s saddle bags, and head out for some adventure!', '`&Remembering that is has been quite some time since you last fed your gelding, you decide this is a perfect time to relax and allow it to graze the field a bit. You doze off enjoying this peaceful serenity.`0', '`&You dismount in the field to allow your gelding to graze for a moment even though it has recently been fully fed.  As you lean back in the grass to watch the clouds, your gelding whickers softly and trots off into the underbrush.  You search for a while before returning to the fields hoping that it\\'ll return.  A short time later, your gelding trots back into the clearing holding its head high, looking much more energized and with a very equine grin on its face.`n`nAnd here you thought geldings weren\\'t equipped that way any longer!`0', 25, 'all', 0)",
"INSERT INTO " . db_prefix("mounts") . " VALUES (3, 'Stallion', 'This noble beast is huge and powerful!', 'Horses', 'a:5:{s:4:\"name\";s:17:\"`&Stallion Attack\";s:8:\"roundmsg\";s:30:\"Your stallion fights with you!\";s:6:\"rounds\";s:2:\"60\";s:6:\"atkmod\";s:3:\"1.2\";s:8:\"activate\";s:7:\"offense\";}', 16, 0, 1, 3, 'You strap your {weapon} to your stallion\\'s saddle bags, and head out for some adventure!', '`&Remembering that is has been quite some time since you last fed your stallion, you decide this is a perfect time to relax and allow it to graze the field a bit. You doze off enjoying this peaceful serenity.`0', '`&You dismount in the field to allow your stallion to graze for a moment even though it has recently been fully fed.  As you lean back in the grass to watch the clouds, your stallion whickers softly and trots off into the underbrush.  You search for a while before returning to the fields hoping that it\\'ll return.  A short time later, your stallion trots back into the clearing holding its head high, looking much more energized and with a very equine grin on its face.`0', 30, 'all', 0)",
),
"0.9.8-prerelease.1"=>array(
"UPDATE " . db_prefix("petitions") . " SET closedate = date WHERE status=2",
"UPDATE " . db_prefix("masters") . " SET creaturewin='Learn to adapt your style, and you shall prevail.' WHERE creaturename='Sensei Noetha'",
"UPDATE " . db_prefix("logdnet") . " SET lastping=lastupdate",
"UPDATE " . db_prefix("accounts") . " SET attack=attack-1,race=\"Troll\" WHERE race='1'",
"UPDATE " . db_prefix("accounts") . " SET defense=defense-1,race=\"Elf\" WHERE race='2'",
"UPDATE " . db_prefix("accounts") . " SET race=\"Human\" WHERE race='3'",
"UPDATE " . db_prefix("accounts") . " SET race=\"Dwarf\" WHERE race='4'",
"UPDATE " . db_prefix("accounts") . " SET race=\"Horrible Gelatinous Blob\" WHERE race='0'",
"UPDATE " . db_prefix("accounts") . " SET location=\"The Boar's Head Inn\" WHERE location='1'",
"UPDATE " . db_prefix("accounts") . " SET location=\"Degolburg\" WHERE location='0'",
"UPDATE " . db_prefix("accounts") . " SET password=md5(password) WHERE length(password) < 32",
"UPDATE " . db_prefix("accounts") . " SET password=md5(password)",
"UPDATE " . db_prefix("nastywords") . " SET type='nasty'",
),
"0.9.8-prerelease.2"=>array(),
"0.9.8-prerelease.3"=>array(),
"0.9.8-prerelease.4"=>array(),
"0.9.8-prerelease.5"=>array(),
"0.9.8-prerelease.6"=>array(
"REPLACE INTO " . db_prefix("masters") . " VALUES (1,'Mireraband',1,'Small Dagger','Well done %w`&, I should have guessed you\\'d grown some.','As I thought, %w`^, your skills are no match for my own!',NULL,NULL,12,2,2)",
"REPLACE INTO " . db_prefix("masters") . " VALUES (2,'Fie',2,'Short Sword','Well done %w`&, you really know how to use your %x.','You should have known you were no match for my %X',NULL,NULL,22,4,4)",
"REPLACE INTO " . db_prefix("masters") . " VALUES (4,'Guth',4,'Spiked Club','Ha!  Hahaha, excellent fight %w`&!  Haven\\'t had a battle like that since I was in the RAF!','Back in the RAF, we\\'d have eaten the likes of you alive!  Go work on your skills some old boy!',NULL,NULL,44,8,8)",
"REPLACE INTO " . db_prefix("masters") . " VALUES (6,'Adwares',6,'Dwarven Battle Axe','Ach!  Y\\' do hold yer %x with skeel!','Har!  Y\\' do be needin moore praktise y\\' wee cub!',NULL,NULL,66,12,12)",
"REPLACE INTO " . db_prefix("masters") . " VALUES (8,'Ceiloth',8,'Orkos Broadsword','Well done %w`&, I can see that great things lie in the future for you!','You are becoming powerful, but not yet that powerful.',NULL,NULL,88,16,16)",
"REPLACE INTO " . db_prefix("masters") . " VALUES (9,'Dwiredan',9,'Twin Swords','Perhaps I should have considered your %x...','Perhaps you\\'ll reconsider my twin swords before you try that again?',NULL,NULL,99,18,18)",
),
"0.9.8-prerelease.7"=>array(),
"0.9.8-prerelease.8"=>array(),
"0.9.8-prerelease.9"=>array(),
"0.9.8-prerelease.10"=>array(),
"0.9.8-prerelease.11"=>array(
"UPDATE " . db_prefix("accounts") . " SET specialty='' WHERE specialty='0'",
),
"0.9.8-prerelease.12"=>array(
"1|UPDATE " . db_prefix("creatures") . " SET forest=1",
"1|UPDATE " . db_prefix("creatures") . " SET graveyard=1 where location=1",
),
"0.9.8-prerelease.13"=>array(),
"0.9.8-prerelease.14"=>array(),
"0.9.8-prerelease.14a"=>array(
"INSERT INTO " . db_prefix("titles") . " VALUES (1, 0, '', 'Farmboy', 'Farmgirl')",
"INSERT INTO " . db_prefix("titles") . " VALUES (2, 1, '', 'Page', 'Page')",
"INSERT INTO " . db_prefix("titles") . " VALUES (3, 2, '', 'Squire', 'Squire')",
"INSERT INTO " . db_prefix("titles") . " VALUES (4, 3, '', 'Gladiator', 'Gladiatrix')",
"INSERT INTO " . db_prefix("titles") . " VALUES (5, 4, '', 'Legionnaire', 'Legioness')",
"INSERT INTO " . db_prefix("titles") . " VALUES (6, 5, '', 'Centurion', 'Centurioness')",
"INSERT INTO " . db_prefix("titles") . " VALUES (7, 6, '', 'Sir', 'Madam')",
"INSERT INTO " . db_prefix("titles") . " VALUES (8, 7, '', 'Reeve', 'Reeve')",
"INSERT INTO " . db_prefix("titles") . " VALUES (9, 8, '', 'Steward', 'Steward')",
"INSERT INTO " . db_prefix("titles") . " VALUES (10, 9, '', 'Mayor', 'Mayoress')",
"INSERT INTO " . db_prefix("titles") . " VALUES (11, 10, '', 'Baron', 'Baroness')",
"INSERT INTO " . db_prefix("titles") . " VALUES (12, 11, '', 'Count', 'Countess')",
"INSERT INTO " . db_prefix("titles") . " VALUES (13, 12, '', 'Viscount', 'Viscountess')",
"INSERT INTO " . db_prefix("titles") . " VALUES (14, 13, '', 'Marquis', 'Marchioness')",
"INSERT INTO " . db_prefix("titles") . " VALUES (15, 14, '', 'Chancellor', 'Chancelloress')",
"INSERT INTO " . db_prefix("titles") . " VALUES (16, 15, '', 'Prince', 'Princess')",
"INSERT INTO " . db_prefix("titles") . " VALUES (17, 16, '', 'King', 'Queen')",
"INSERT INTO " . db_prefix("titles") . " VALUES (18, 17, '', 'Emperor', 'Empress')",
"INSERT INTO " . db_prefix("titles") . " VALUES (19, 18, '', 'Angel', 'Angel')",
"INSERT INTO " . db_prefix("titles") . " VALUES (20, 19, '', 'Archangel', 'Archangel')",
"INSERT INTO " . db_prefix("titles") . " VALUES (21, 20, '', 'Principality', 'Principality')",
"INSERT INTO " . db_prefix("titles") . " VALUES (22, 21, '', 'Power', 'Power')",
"INSERT INTO " . db_prefix("titles") . " VALUES (23, 22, '', 'Virtue', 'Virtue')",
"INSERT INTO " . db_prefix("titles") . " VALUES (24, 23, '', 'Dominion', 'Dominion')",
"INSERT INTO " . db_prefix("titles") . " VALUES (25, 24, '', 'Throne', 'Throne')",
"INSERT INTO " . db_prefix("titles") . " VALUES (26, 25, '', 'Cherub', 'Cherub')",
"INSERT INTO " . db_prefix("titles") . " VALUES (27, 26, '', 'Seraph', 'Seraph')",
"INSERT INTO " . db_prefix("titles") . " VALUES (28, 27, '', 'Demigod', 'Demigoddess')",
"INSERT INTO " . db_prefix("titles") . " VALUES (29, 28, '', 'Titan', 'Titaness')",
"INSERT INTO " . db_prefix("titles") . " VALUES (30, 29, '', 'Archtitan', 'Archtitaness')",
"INSERT INTO " . db_prefix("titles") . " VALUES (31, 30, '', 'Undergod', 'Undergoddess')",
"INSERT INTO " . db_prefix("titles") . " VALUES (32, 31, '', 'God', 'Goddess')",
),
"1.0.0"=>array(),
"1.0.1"=>array(),
"1.0.2"=>array(),
"1.0.3"=>array(),
"1.0.4"=>array(),
"1.0.5"=>array(),
"1.0.6"=>array(),
"1.1.0 Dragonprime Edition"=>array(
"UPDATE " . db_prefix("accounts") . " SET clanrank = clanrank * 10",
"INSERT INTO " . db_prefix("settings") . " VALUES ('newdaycron', '0')",
"INSERT INTO " . db_prefix("settings") . " VALUES ('charset', 'ISO-8859-1')",
"INSERT INTO " . db_prefix("settings") . " VALUES ('allowspecialswitch', '1')",
),
"1.1.1 Dragonprime Edition"=>array(
"INSERT INTO " . db_prefix("settings") . " VALUES ('allowclans','1')",
"INSERT INTO " . db_prefix("settings") . " VALUES ('resurrectionturns','-6')",

"DROP TABLE IF EXISTS " . db_prefix("module_navhooks") . ";",
"DROP TABLE IF EXISTS " . db_prefix("module_pagehooks") . ";",
"DROP TABLE IF EXISTS " . db_prefix("module_settingdesc") . ";",
"DROP TABLE IF EXISTS " . db_prefix("module_prefdesc") . ";",
"DROP TABLE IF EXISTS " . db_prefix("items") . ";",

"ALTER TABLE " . db_prefix("creatures"). " DROP oldcreatureexp;",

"INSERT INTO " . db_prefix("settings") . " VALUES ('serverlanguages','en,English,fr,Fran�ais,dk,Danish,de,Deutsch,es,Espa�ol,it,Italian')",
"INSERT INTO " . db_prefix("creatures") . " $creaturefields111 VALUES (320, 'Gypsy Bandit', 14, 'Gemmed Dagger', 'You''re dead, he''s free to take what he will.', 'That will put an end to his thieving days.', 499, 172, 145, 27, 20, 'global \$badguy, \$session;\r\n\r\nif (!isset(\$badguy[\\'spellpoints\\'])) {\r\n	\$badguy[\\'spellpoints\\'] = 1;\r\n}\r\n\r\n\$gold = round(\$session[\\'user\\'][\\'gold\\'] * 0.2);\r\nif (e_rand(0,7) == 0 && \$gold > 200 && \$badguy[\\'spellpoints\\'] == 1) {\r\n	rawoutput(\"<br /><b><span style=''color: white''>The pickpocket takes <span style=''color: gold''>\$gold gold</span>!</span></b><br /><br />\");\r\n	\$session[\\'user\\'][\\'gold\\'] -= \$gold;\r\n	\$badguy[\\'creaturegold\\'] += \$gold;\r\n	\$badguy[\\'spellpoints\\']--;\r\n}', 'Talisman', 1, 0)",

"INSERT INTO " . db_prefix("companions") . " (`companionid`, `name`, `category`, `description`, `attack`, `attackperlevel`, `defense`, `defenseperlevel`, `maxhitpoints`, `maxhitpointsperlevel`, `abilities`, `cannotdie`, `cannotbehealed`, `companionlocation`, `companionactive`, `companioncostdks`, `companioncostgems`, `companioncostgold`, `jointext`, `dyingtext`, `allowinshades`, `allowinpvp`, `allowintrain`) VALUES (1, 'Mortimer teh javelin man', 'Knight', 'A rough and ready warrior.  Beneath his hardened exterior, one can detect a man of strong honour.', 5, 2, 1, 2, 20, 20, 'a:4:{s:5:\"fight\";s:1:\"1\";s:4:\"heal\";s:1:\"0\";s:5:\"magic\";s:1:\"0\";s:6:\"defend\";b:0;}', 0, 0, '".getsetting("villagename", LOCATION_FIELDS)."', 1, 0, 4, 573, '`^Greetings unto thee, my friend.  Let us go forth and conquer the evils of this world together!', '`4Argggggh!  I am slain!  Shuffling off my mortal coil.  Fare thee well, my friends.', 1, 0, 0)",
"INSERT INTO " . db_prefix("companions") . " (`companionid`, `name`, `category`, `description`, `attack`, `attackperlevel`, `defense`, `defenseperlevel`, `maxhitpoints`, `maxhitpointsperlevel`, `abilities`, `cannotdie`, `cannotbehealed`, `companionlocation`, `companionactive`, `companioncostdks`, `companioncostgems`, `companioncostgold`, `jointext`, `dyingtext`, `allowinshades`, `allowinpvp`, `allowintrain`) VALUES (2, 'Florenz', 'Healer', 'With a slight build, Florenz is better suited as a healer than a fighter.', 1, 1, 5, 5, 15, 10, 'a:4:{s:4:\"heal\";s:1:\"2\";s:5:\"magic\";s:1:\"0\";s:5:\"fight\";b:0;s:6:\"defend\";b:0;}', 0, 0, '".getsetting("villagename", LOCATION_FIELDS)."', 1, 0, 3, 1000, 'Thank ye for thy faith in my skills.  I shall endeavour to keep ye away from Ramius'' claws.', 'O Discordia!', 1, 0, 0)",
),
"1.1.1 Dragonprime Edition +nb"=>array(),
"1.1.1.0 Dragonprime Edition +nb"=>array(
	"INSERT INTO " . db_prefix("deathmessages") . " VALUES (0,'`4{goodguyname}`4 has been slain {where} by `4{badguy}`4.',1,0,1,'Nightborn')",
	"INSERT INTO " . db_prefix("deathmessages") . " VALUES (0,'`4{goodguyname}`4 has been defeated {where} by `4{badguy}`4.',0,1,1,'Nightborn')",
	),
"1.1.1.1 Dragonprime Edition +nb"=>array(
	//since the change of the %w stuff to some more sensible stuff, we need to replace the text in the old taunts to fit in
	"UPDATE " . db_prefix("taunts") . " SET taunt=REPLACE(taunt,'%w','{goodguy}')",
	"UPDATE " . db_prefix("taunts") . " SET taunt=REPLACE(taunt,'%W','{badguy}')",
	"UPDATE " . db_prefix("taunts") . " SET taunt=REPLACE(taunt,'%x','{goodguyweapon}')",
	"UPDATE " . db_prefix("taunts") . " SET taunt=REPLACE(taunt,'%X','{badguyweapon}')",
	"UPDATE " . db_prefix("taunts") . " SET taunt=REPLACE(taunt,'%a','{goodguyarmor}')",
	"UPDATE " . db_prefix("taunts") . " SET taunt=REPLACE(taunt,'%s','{himher}')",
	"UPDATE " . db_prefix("taunts") . " SET taunt=REPLACE(taunt,'%p','{hisher}')",
	"UPDATE " . db_prefix("taunts") . " SET taunt=REPLACE(taunt,'%o','{heshe}')",
	//masters
	"UPDATE " . db_prefix("masters") . " SET creaturewin=REPLACE(creaturewin,'%w','{goodguy}')",
	"UPDATE " . db_prefix("masters") . " SET creaturewin=REPLACE(creaturewin,'%W','{badguy}')",
	"UPDATE " . db_prefix("masters") . " SET creaturewin=REPLACE(creaturewin,'%x','{goodguyweapon}')",
	"UPDATE " . db_prefix("masters") . " SET creaturewin=REPLACE(creaturewin,'%X','{badguyweapon}')",
	"UPDATE " . db_prefix("masters") . " SET creaturewin=REPLACE(creaturewin,'%a','{goodguyarmor}')",
	"UPDATE " . db_prefix("masters") . " SET creaturewin=REPLACE(creaturewin,'%s','{himher}')",
	"UPDATE " . db_prefix("masters") . " SET creaturewin=REPLACE(creaturewin,'%p','{hisher}')",
	"UPDATE " . db_prefix("masters") . " SET creaturewin=REPLACE(creaturewin,'%o','{heshe}')",
	//masters part 2
	"UPDATE " . db_prefix("masters") . " SET creaturelose=REPLACE(creaturelose,'%w','{goodguy}')",
	"UPDATE " . db_prefix("masters") . " SET creaturelose=REPLACE(creaturelose,'%W','{badguy}')",
	"UPDATE " . db_prefix("masters") . " SET creaturelose=REPLACE(creaturelose,'%x','{goodguyweapon}')",
	"UPDATE " . db_prefix("masters") . " SET creaturelose=REPLACE(creaturelose,'%X','{badguyweapon}')",
	"UPDATE " . db_prefix("masters") . " SET creaturelose=REPLACE(creaturelose,'%a','{goodguyarmor}')",
	"UPDATE " . db_prefix("masters") . " SET creaturelose=REPLACE(creaturelose,'%s','{himher}')",
	"UPDATE " . db_prefix("masters") . " SET creaturelose=REPLACE(creaturelose,'%p','{hisher}')",
	"UPDATE " . db_prefix("masters") . " SET creaturelose=REPLACE(creaturelose,'%o','{heshe}')",
	),
"1.1.1.2 Dragonprime Edition +nb"=>array(),
"1.2.0 +nb Edition"=>array(),
"1.2.1 +nb Edition"=>array(),
"1.2.2 +nb Edition"=>array(),
"1.2.3 +nb Edition"=>array(),
"1.2.4 +nb Edition"=>array(),
"1.2.5 +nb Edition"=>array(),
);
?>
