doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        host: '%env(DATABASE_HOST)%'
        port: 3306
        driver: '%env(DATABASE_DRIVER)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '%env(DATABASE_VERSION)%'
    orm:
        auto_mapping: true
