doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        host: '%env(DATABASE_HOST)%'
        port: 3306
        driver: '%env(DATABASE_DRIVER)%'
        charset: utf8
        mapping_types:
            enum: string
        types:
            datetime: Lotgd\Core\Doctrine\DBAL\DateTimeType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '%env(DATABASE_VERSION)%'
        default_table_options:
            # Affects schema-tool. If absent, DBAL chooses defaults
            # based on the platform.
            charset: utf8
            collate: utf8_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        quote_strategy: doctrine.orm.quote_strategy.ansi
        auto_mapping: true
        default_repository_class: Lotgd\Core\Doctrine\ORM\EntityRepository
        mappings:
            Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/core/Entity'
                prefix: 'Lotgd\Core\Entity'
                alias: LotgdCore
            Local:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/local/Entity'
                prefix: 'Lotgd\Local\Entity'
                alias: LotgdLocal
        dql:
            string_functions:
                inet_aton: DoctrineExtensions\Query\Mysql\InetAton
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round
                rand: DoctrineExtensions\Query\Mysql\Rand
            datetime_functions:
                month: DoctrineExtensions\Query\Mysql\Month
                year: DoctrineExtensions\Query\Mysql\Year
                date: DoctrineExtensions\Query\Mysql\Date
