lotgd_core_advertising:
    enable: true
    providers:
        adsense:
            type: adsense
            enable: true
            client: null # "data-ad-client" ca-pub-XXXXXXX11XXX9
            banners: # Banners of ads (As many as you need with the same format)
                ad_header:
                    style: 'display:block' # style="" tag in <ins>
                    slot: 0 #  "data-ad-slot" Slot ID of Ad block 8XXXXX1
                    format: 'auto' # "data-ad-format" Values: "rectangle", "vertical" or "horizontal"
                    responsive: true # "data-full-width-responsive"
                ad_column_navigation_bottom:
                    style: 'display:block'
                    slot: 0
                    format: 'auto'
                    responsive: true
