security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Custom firewall for the admin area of the URL
        admin:
            pattern: ^/grotto/_admin
            provider: lotgd_admin_user_provider
            user_checker: Lotgd\Bundle\AdminBundle\Security\UserChecker
            form_login:
                login_path: lotgd_admin_login
                use_forward: false
                check_path: lotgd_admin_login
                failure_path: null
            logout:
                path: lotgd_admin_logout
                target: lotgd_admin_login
            anonymous: lazy
            guard:
                authenticators:
                    - Lotgd\Bundle\AdminBundle\Security\LoginFormAuthenticator
            # entry_point: form_login
        main:
            anonymous: lazy
            provider: lotgd_core_user_provider
            user_checker: Lotgd\Bundle\UserBundle\Security\UserChecker
            guard:
                authenticators:
                    - Lotgd\Bundle\UserBundle\Security\LoginFormAuthenticator
            logout:
                path: lotgd_core_logout
                # where to redirect after logout
                # target: app_any_route

            # https://symfony.com/doc/current/security/remember_me.html
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                secure: true
                httponly: true
                samesite: strict

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/grotto/_admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/grotto/_admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Admin panel can only be access by admin users.
        - { path: ^/grotto/_admin/, roles: ROLE_ADMIN }
        # All routes of game start with /game/
        # You need prefixed all routes that is part of game this /game/
        # So all routers that start with this is for authenticated users
        - { path: ^/game/, roles: IS_AUTHENTICATED_FULLY }
        # By default all routes are public access.
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
