sylius_theme:
    sources:
        filesystem:
            enabled: true
            filename: theme.json
            scan_depth: 1
            directories:
                - "%kernel.project_dir%/themes"
