twig:
    default_path: '%kernel.project_dir%/templates'
    strict_variables: false
    autoescape: false
    auto_reload: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/templates_modules': 'module'
    # Globals variables
    globals:
        userPre: ~ # Not remove, if for avoid errors
        user: ~ # Not remove, if for avoid errors
        sessionPre: ~ # Not remove, if for avoid errors
        session: ~ # Not remove, if for avoid errors
    form_themes: [
        'form/semantic-ui-form-theme.html.twig'
    ]
