---
version: "2"
checks:
    argument-count:
        enabled: true
    complex-logic:
        enabled: true
        config:
            threshold: 5
    file-lines:
        enabled: true
        config:
            threshold: 350
    method-complexity:
        enabled: true
        config:
            threshold: 15
    method-count:
        enabled: true
        config:
            threshold: 25
    method-lines:
        enabled: true
        config:
            threshold: 35
    nested-control-flow:
        enabled: true
        config:
            threshold: 5
    return-statements:
        enabled: true
        config:
            threshold: 5
    similar-code:
        enabled: true
    identical-code:
        enabled: true
plugins:
    editorconfig:
        enabled: true
        channel: beta
        exclude_patterns:
            - "images/"
            - "docs/"
            - "release/"
            - "storage/"
            - "**/*.ico"
            - "**/*.png"
            - "**/*.zip"
            - "**/*.phar"
        config:
            editorconfig: .editorconfig
    nodesecurity:
        enabled: true
    eslint:
        enabled: true
        channel: "eslint-5"
    sonar-php:
        enabled: true
        exclude_patterns:
            - "assets/"
            - "error_docs/"
            - "gulp/"
            - "docs/"
            - "public/images/"
            - "public/css/"
            - "public/js/"
            - "public/themes/"
            - "templates/"
            - "templates_core/"
            - "templates_modules/"
            - "storage/"
            - "vendor/"
            - "**/*.ico"
            - "**/*.png"
        config:
            file_extensions: "php"
        checks:
            php:S3776:
                enabled: false
            php:S1192:
                enabled: false
            php:S1448:
                enabled: false
    phpmd:
        enabled: true
        exclude_patterns:
            - "assets/"
            - "error_docs/"
            - "docs/"
            - "gulp/"
            - "public/images/"
            - "public/css/"
            - "public/js/"
            - "public/themes/"
            - "templates/"
            - "templates_core/"
            - "templates_modules/"
            - "storage/"
            - "vendor/"
        config:
            file_extensions: "php"
            rulesets: "phpmd.xml"
        checks:
            CleanCode/StaticAccess:
                enabled: false
            Naming/BooleanGetMethodName:
                enabled: false
    phpcodesniffer:
        enabled: false
        exclude_patterns:
            - "assets/"
            - "error_docs/"
            - "gulp/"
            - "docs/"
            - "public/images/"
            - "public/css/"
            - "public/js/"
            - "public/themes/"
            - "templates/"
            - "templates_core/"
            - "templates_modules/"
            - "storage/"
            - "vendor/"
        config:
            file_extensions: "php"
            standard: "PSR2,phpcs.xml"
        checks:
            Squiz Functions MultiLineFunctionDeclaration OneParamPerLine:
                enabled: false
            Squiz ControlStructures ControlSignature SpaceAfterCloseParenthesis:
                enabled: false
            Squiz Functions MultiLineFunctionDeclaration NewlineBeforeOpenBrace:
                enabled: false
            Squiz ControlStructures ControlSignature SpaceAfterCloseBrace:
                enabled: false
            Squiz ControlStructures ControlSignature SpaceAfterKeyword:
                enabled: false
exclude_patterns:
    - "config/"
    - "db/"
    - "docs/"
    - "dist/"
    - "features/"
    - "**/node_modules/"
    - "script/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"
    - "Tests/"
    - "vendor/"
    - "**/*_test.go"
    - "**/*.d.ts"
    - "**/*.zip"
    - "**/*.phar"
    - "semantic/"
    - "composer.lock"
    - "package-lock.json"
    - "public/js/jqueryCookieGuard.1.1.0.js"
