---
version: "2"
checks:
    argument-count:
        enabled: true
    complex-logic:
        enabled: true
    file-lines:
        enabled: true
    method-complexity:
        enabled: true
    method-count:
        enabled: true
    method-lines:
        enabled: true
    nested-control-flow:
        enabled: true
    return-statements:
        enabled: true
    similar-code:
        enabled: true
    identical-code:
        enabled: true
plugins:
    sonar-php:
        enabled: true
        config:
            file_extensions: "php"
            exclude_patterns:
                - "**/assets/"
                - "**/error_docs/"
                - "**/gulp/"
                - "**/images/"
                - "**/resources/"
                - "**/semantic/"
                - "**/templates/"
                - "**/themes/"
    phpmd:
        enabled: true
        config:
            file_extensions:
                - php
            exclude_patterns:
                - "**/assets/"
                - "**/error_docs/"
                - "**/gulp/"
                - "**/images/"
                - "**/resources/"
                - "**/semantic/"
                - "**/templates/"
                - "**/themes/"
    nodesecurity:
        enabled: true
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php"
            exclude_patterns:
                - "**/assets/"
                - "**/error_docs/"
                - "**/gulp/"
                - "**/images/"
                - "**/resources/"
                - "**/semantic/"
                - "**/templates/"
                - "**/themes/"
    phan:
        enabled: true
        config:
            file_extensions: "php"
            backward-compatibility-checks: true
            dead-code-detection: true
            exclude_patterns:
                - "**/assets/"
                - "**/error_docs/"
                - "**/gulp/"
                - "**/images/"
                - "**/resources/"
                - "**/semantic/"
                - "**/templates/"
                - "**/themes/"
exclude_patterns:
    - "config/"
    - "db/"
    - "dist/"
    - "features/"
    - "**/node_modules/"
    - "script/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"
    - "Tests/"
    - "**/vendor/"
    - "**/*_test.go"
    - "**/*.d.ts"
    - "**/semantic/src/definitions/"
    - "**/semantic/task/"
