---
version: "2"
checks:
    argument-count:
        enabled: true
    complex-logic:
        enabled: true
    file-lines:
        enabled: true
    method-complexity:
        enabled: true
    method-count:
        enabled: true
    method-lines:
        enabled: true
    nested-control-flow:
        enabled: true
    return-statements:
        enabled: true
    similar-code:
        enabled: true
    identical-code:
        enabled: true
plugins:
    nodesecurity:
        enabled: true
    sonar-php:
        enabled: true
        exclude_patterns:
            - "**/assets/"
            - "**/error_docs/"
            - "**/gulp/"
            - "**/images/"
            - "**/resources/"
            - "**/templates/"
            - "**/themes/"
            - "**/*.ico"
            - "**/*.png"
        config:
            file_extensions: "php"
    phpmd:
        enabled: true
        exclude_patterns:
            - "**/assets/"
            - "**/error_docs/"
            - "**/gulp/"
            - "**/images/"
            - "**/resources/"
            - "**/templates/"
            - "**/themes/"
        config:
            file_extensions:
                - php
            rulesets: "cleancode,codesize,controversial,design,naming,unusedcode,phpmd-ruleset.xml"
    phpcodesniffer:
        enabled: true
        exclude_patterns:
            - "**/assets/"
            - "**/error_docs/"
            - "**/gulp/"
            - "**/images/"
            - "**/resources/"
            - "**/templates/"
            - "**/themes/"
        config:
            file_extensions: "php"
    phan:
        enabled: false
        exclude_patterns:
            - "**/assets/"
            - "**/error_docs/"
            - "**/gulp/"
            - "**/images/"
            - "**/resources/"
            - "**/templates/"
            - "**/themes/"
        config:
            file_extensions: "php"
            backward-compatibility-checks: true
            dead-code-detection: true
exclude_patterns:
    - "config/"
    - "db/"
    - "dist/"
    - "features/"
    - "**/node_modules/"
    - "script/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"
    - "Tests/"
    - "**/vendor/"
    - "**/*_test.go"
    - "**/*.d.ts"
    - "**/semantic/"
