---
version: "2"

plugins:
    sonar-php:
        enabled: true
        config:
            file_extensions: "php"
    phpmd:
        enabled: true
        file_extensions:
            - php
    nodesecurity:
        enabled: true
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php"
    phan:
        enabled: true
        config:
            file_extensions: "php"
            backward-compatibility-checks: true
            dead-code-detection: true
exclude_patterns:
    - "config/"
    - "db/"
    - "dist/"
    - "features/"
    - "**/node_modules/"
    - "script/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"
    - "Tests/"
    - "**/vendor/"
    - "**/*_test.go"
    - "**/*.d.ts"
    - "**/semantic/src/definitions/"
    - "**/semantic/task/"
