---
version: "2"
checks:
    argument-count:
        enabled: true
    complex-logic:
        enabled: true
    file-lines:
        enabled: true
        config:
            threshold: 350
    method-complexity:
        enabled: true
        config:
            threshold: 10
    method-count:
        enabled: true
    method-lines:
        enabled: true
        config:
            threshold: 35
    nested-control-flow:
        enabled: true
    return-statements:
        enabled: true
    similar-code:
        enabled: true
    identical-code:
        enabled: true
plugins:
    nodesecurity:
        enabled: true
    sonar-php:
        enabled: false
        exclude_patterns:
            - "assets/"
            - "cache/"
            - "crawl/"
            - "error_docs/"
            - "gulp/"
            - "images/"
            - "logd_snapshots/"
            - "resources/"
            - "templates/"
            - "themes/"
            - "**/*.ico"
            - "**/*.png"
        config:
            file_extensions: "php"
    phpmd:
        enabled: true
        exclude_patterns:
            - "assets/"
            - "cache/"
            - "crawl/"
            - "error_docs/"
            - "gulp/"
            - "images/"
            - "logd_snapshots/"
            - "resources/"
            - "templates/"
            - "themes/"
        config:
            file_extensions:
                - php
            rulesets: "cleancode,controversial,design,naming,unusedcode"
    phpcodesniffer:
        enabled: false
        exclude_patterns:
            - "assets/"
            - "cache/"
            - "crawl/"
            - "error_docs/"
            - "gulp/"
            - "images/"
            - "logd_snapshots/"
            - "resources/"
            - "templates/"
            - "themes/"
        config:
            file_extensions: "php"
            standard: "PSR2"
            file: "phpcs.xml"
    phan:
        enabled: true
        exclude_patterns:
                - "assets/"
                - "cache/"
                - "crawl/"
                - "error_docs/"
                - "gulp/"
                - "images/"
                - "logd_snapshots/"
                - "resources/"
                - "templates/"
                - "themes/"
                - "vendor/**/*"
        config:
            file_extensions: "php"
            backward-compatibility-checks: true
            dead-code-detection: true
            exclude_analysis_directory_list:
                - "assets/"
                - "cache/"
                - "crawl/"
                - "error_docs/"
                - "gulp/"
                - "images/"
                - "logd_snapshots/"
                - "resources/"
                - "templates/"
                - "themes/"
                - "vendor/**/*"
exclude_patterns:
    - "config/"
    - "db/"
    - "dist/"
    - "features/"
    - "**/node_modules/"
    - "script/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"
    - "Tests/"
    - "vendor/"
    - "**/*_test.go"
    - "**/*.d.ts"
    - "semantic/"
    - "resources/jqueryCookieGuard.1.1.0.js"
