linters:
    phpcs:
        standard: PSR2
        fixer: false
    eslint:
        config: .eslintrc.js
        fixer: true
files:
    ignore:
        - 'vendor/*'
        - 'bower_components/*'
        - 'node_modules/*'
        - 'dist/'
        - 'semantic/*'
fixers:
    enable: true
