services:
  database:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 350M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 5s

  webserver:
    restart: always
    volumes:
      # Shared files between deployments
      - source_uploads:/app/public/uploads # For example, files uploaded by users
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 250M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 5s

  worker_async:
    image: ${DOCKER_IMAGE_NAME_WEBSERVER}
    entrypoint: '/usr/local/bin/worker_async_entrypoint.sh'
    restart: always
    healthcheck:
      test: [ "CMD", "php", "bin/console", "about" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 175M

  worker_scheduler:
    image: ${DOCKER_IMAGE_NAME_WEBSERVER}
    entrypoint: '/usr/local/bin/worker_scheduler_entrypoint.sh'
    restart: always
    healthcheck:
      test: [ "CMD", "php", "bin/console", "about" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - scheduler_cache:/app/storage/scheduler
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 175M

volumes:
  source_uploads:
  scheduler_cache:
