name: lotgd_core

services:
    database:
        image: mariadb:11.4.4
        ports:
            - "3306:3306"
        environment:
            MARIADB_AUTO_UPGRADE: true
            MARIADB_DATABASE: ${DATABASE_NAME}
            MARIADB_USER: ${DATABASE_USER}
            MARIADB_PASSWORD_FILE: /run/secrets/db_password
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_password
            # MARIADB_RANDOM_ROOT_PASSWORD: 0
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - database_data:/var/lib/mysql
        secrets:
            - db_password

    apache:
        build:
            context: .docker/apache
            target: dev
            args:
                VERSION: 2.4.62
        ports:
            - "8080:443"
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
        volumes:
            - ./:/var/www/html
            ## Conf
            - ./.docker/apache/conf/directory.conf:/usr/local/apache2/conf/d/directory.conf
            - ./.docker/apache/conf/httpd-ssl.conf:/usr/local/apache2/conf/d/httpd-ssl.conf
            ## Sites
            - ./.docker/apache/sites/dev/000-default.conf:/usr/local/apache2/conf/sites/000-default.conf
            - ./.docker/apache/sites/dev/default-ssl.conf:/usr/local/apache2/conf/sites/default-ssl.conf
        depends_on:
            - php
            - database
    php:
        build:
            context: .docker/php
            target: dev
            args:
                VERSION: '7.4'
        environment:
            SYMFONY_REQUIRE: '4.4.*'
        healthcheck:
            test: php -v || exit 1
        volumes:
            - ./:/var/www/html
            ## PHP Conf
            - ./.docker/php/conf.d/common.ini:/usr/local/etc/php/conf.d/common.ini
            - ./.docker/php/conf.d/disable_functions.ini:/usr/local/etc/php/conf.d/disable_functions.ini
            ## PHP Conf Dev
            - ./.docker/php/conf.d/dev/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/php/conf.d/dev/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

secrets:
    db_password:
        environment: DATABASE_PASSWORD

volumes:
    database_data:
