services:
  ###> doctrine/doctrine-bundle ###
  database:
    restart: no
    ports:
      - "13306:3306"
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}_dev
      MARIADB_USER: ${DATABASE_USER}_dev
    volumes:
      - database_data_dev:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###

  database_test:
    restart: no
    extends:
      file: compose.yaml
      service: database
    ports:
      - "13307:3306"
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}_test
      MARIADB_USER: ${DATABASE_USER}_test
    volumes:
      - database_data_test:/var/lib/mysql

  webserver:
    restart: no
    volumes:
      - ./:/app

  ###> symfony/mailer ###
  mailer:
    restart: no
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  # Used to publish the application
  deployer:
    image: idmarinas/php:8.4-deployer
    privileged: true
    healthcheck:
      test: php -v || exit 1
    volumes:
      - ./:/app
      - /var/lib/docker  # Volumen anónimo temporal
      ## SSH
      - ssh_key:/root/.ssh

volumes:
  database_data_dev:
  database_data_test:
  ssh_key:
    external: true
