<?php
	$dwid=$args['dwid'];
	set_module_objpref("dwellings",$dwid,"chair",0);
	set_module_objpref("dwellings",$dwid,"custchair","");
	set_module_objpref("dwellings",$dwid,"chairstress",0);
	set_module_objpref("dwellings",$dwid,"table",0);
	set_module_objpref("dwellings",$dwid,"custtable","");
	set_module_objpref("dwellings",$dwid,"tablestress",0);
	set_module_objpref("dwellings",$dwid,"bed",0);
	set_module_objpref("dwellings",$dwid,"custbed","");
	set_module_objpref("dwellings",$dwid,"bedstress",0);
?>