doctrine:
    dbal:
        charset: utf8
        mapping_types:
            enum: string
        types:
            datetime: Lotgd\Bundle\CoreBundle\Doctrine\DBAL\DateTimeType

        default_table_options:
            # Affects schema-tool. If absent, DBAL chooses defaults
            # based on the platform.
            charset: utf8
            collate: utf8_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        quote_strategy: doctrine.orm.quote_strategy.ansi
        # default_repository_class: Lotgd\Core\Doctrine\ORM\EntityRepository
        mappings:
            LotgdCoreBundle:
                is_bundle: true
                type: annotation
                prefix: 'Lotgd\Bundle\CoreBundle\Entity'
                alias: LotgdCore
        dql:
            string_functions:
                inet_aton: DoctrineExtensions\Query\Mysql\InetAton
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round
                rand: DoctrineExtensions\Query\Mysql\Rand
            datetime_functions:
                month: DoctrineExtensions\Query\Mysql\Month
                year: DoctrineExtensions\Query\Mysql\Year
                date: DoctrineExtensions\Query\Mysql\Date
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
