doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'Lotgd\Bundle\CoreBundle': '@LotgdCoreBundle/Migration'

    # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    organize_migrations: BY_YEAR

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'lotgd_migration_versions'