# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    csrf_protection: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        name: LegendOfTheGreenDragon
        enabled: true
        handler_id: null
        cookie_secure: true
        cookie_samesite: lax
        use_cookies: true
