<?php

$tauntsTable = DB::prefix('taunts');
$weaponsTable = DB::prefix('weapons');
$armorTable = DB::prefix('armor');

return [
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6Just wait for my revenge, `4{badguy}`6. It will be swift!`5\" {goodguy} declares.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6I\\'m really going to enjoy this new `4{weapon}`6 that {goodguy}`6 had,`5\" exclaimed {badguy}.','joe')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6Aah, so `bthat\\'s`b what `4{creatureweapon}`6 is for!`5\" exclaimed {badguy}','joe')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6Oh man!  I didn\\'t think you had it in you, `5{badguy}`6,`5\" {goodguy} exclaims.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5{badguy} was overheard saying, \"`6{hisher} `4{weapon}`6 was no match for my `4{creatureweapon}`6!`5\"','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6You know, you really shouldn\\'t have a `4{weapon}`6 unless you know how to use it,`5\" suggested {badguy}.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6`bARRRGGGGGGG`b!!`5\" {goodguy} screams in frustration.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6How could I be so feeble?`5\" {goodguy} laments.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6I must not be as sturdy as I thought...!`5\" {goodguy} concedes.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6Watch your back, `4{badguy}`6, I am coming for you!`5\" {goodguy} warns.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6This both sucks and blows!`5\" wails {goodguy}.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6I see London, I see France, I see `4{goodguy}\\'s`6 underpants!`5\" reveals {badguy}.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6The Healer\\'s Hut can\\'t help you now, `4{goodguy}`6!`5\" chides {badguy}.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5{badguy} smiles.  \"`6You are too slow.  You are too weak.`5\"','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5{goodguy} bangs {hisher} head against a stone...\"`6Stupid, stupid, stupid!`5\" {heshe} was heard to say.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6My ego can\\'t take much more of this bruising!`5\" exclaims {goodguy}.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6Why didn\\'t I become a successful doctor like my father suggested?`5\" wonders {goodguy} aloud.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6Maybe `bnext`b time you won\\'t be so cocky!`5\" laughs {badguy}','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6A baby could wield a `4{weapon} `6better than that!`5\" {badguy} proclaims.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6You should have just stayed in bed,`5\" {badguy} suggests.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6Well isn\\'t that a kick in the crotch?!`5\" {goodguy} observes.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6Come back when you learn how to fight,`5\" {baguy} scoffs.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6Next time, eat your Wheaties,`5\" {badguy} suggests.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5 \"`6You are dishonorable, `4{badguy}`6!`5\" {goodguy} cries.','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`4{goodguy}`6, your lack of posture is a disgrace,`5\" {badguy}  states. ','Bluspring')",
	"INSERT INTO $tauntsTable VALUES (0,'`5\"`6You know, `4{goodguy}`6 really had it coming to {himher} after all those things `bI`b said about `b{hisher}`b mom`5,\" commented {badguy}.','Joe')",

	"INSERT INTO $weaponsTable VALUES (0,'Rake',48,1,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Trowel',225,2,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Spade',585,3,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Adze',990,4,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Gardening Hoe',1575,5,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Torch',2250,6,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Pitchfork',2790,7,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Shovel',3420,8,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Hedge Trimmers',4230,9,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Hatchet',5040,10,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Carving Knife',5850,11,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Rusty Iron Wood-Chopping Axe',6840,12,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Dull Steel Wood-chopping Axe',8010,13,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Sharp Steel Wood-chopping Axe',9000,14,0)",
	"INSERT INTO $weaponsTable VALUES (0,'Woodsman\\'s Axe',10350,15,0)",

	"INSERT INTO $armorTable VALUES (0,'Fuzzy Slippers',48,1,0)",
	"INSERT INTO $armorTable VALUES (0,'Flannel Pajamas',225,2,0)",
	"INSERT INTO $armorTable VALUES (0,'Homespun Longjohns',585,3,0)",
	"INSERT INTO $armorTable VALUES (0,'Homespun Undershirt',990,4,0)",
	"INSERT INTO $armorTable VALUES (0,'Knitted Socks',1575,5,0)",
	"INSERT INTO $armorTable VALUES (0,'Knitted Gloves',2250,6,0)",
	"INSERT INTO $armorTable VALUES (0,'Old Leather Boots',2790,7,0)",
	"INSERT INTO $armorTable VALUES (0,'Homespun Pants',3420,8,0)",
	"INSERT INTO $armorTable VALUES (0,'Homespun Tunic',4230,9,0)",
	"INSERT INTO $armorTable VALUES (0,'Gypsy Cape',5040,10,0)",
	"INSERT INTO $armorTable VALUES (0,'Old Leather Cap',5850,11,0)",
	"INSERT INTO $armorTable VALUES (0,'Old Leather Bracers',6840,12,0)",
	"INSERT INTO $armorTable VALUES (0,'Traveller\\'s Shield',8010,13,0)",
	"INSERT INTO $armorTable VALUES (0,'Old Leather Pants',9000,14,0)",
	"INSERT INTO $armorTable VALUES (0,'Old Leather Tunic',10350,15,0)",

	"INSERT INTO $weaponsTable VALUES (0,'Pebbles',48,1,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Stones',225,2,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Rocks',585,3,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Small Treebranch',990,4,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Large Treebranch',1575,5,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Thickly Padded Sparring Pole',2250,6,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Thinly Padded Sparring Pole',2790,7,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Wooden Stave',3420,8,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Wooden Practice Sword',4230,9,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Blunt Bronze Short Sword',5040,10,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Crafted Bronze Short Sword',5850,11,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Rusty Steel Short Sword',6840,12,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Dull Steel Short Sword',8010,13,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Sharp Steel Short Sword',9000,14,1)",
	"INSERT INTO $weaponsTable VALUES (0,'Pages\\'s Short Sword',10350,15,1)",

	"INSERT INTO $armorTable VALUES (0,'Flip-Flops',48,1,1)",
	"INSERT INTO $armorTable VALUES (0,'Swimsuit and Towel',225,2,1)",
	"INSERT INTO $armorTable VALUES (0,'Cotton Undershirt',585,3,1)",
	"INSERT INTO $armorTable VALUES (0,'Wool Socks',990,4,1)",
	"INSERT INTO $armorTable VALUES (0,'Wool Gloves',1575,5,1)",
	"INSERT INTO $armorTable VALUES (0,'Leather Boots',2250,6,1)",
	"INSERT INTO $armorTable VALUES (0,'Leather Cap',2790,7,1)",
	"INSERT INTO $armorTable VALUES (0,'Leather Bracers',3420,8,1)",
	"INSERT INTO $armorTable VALUES (0,'Leather Leggings',4230,9,1)",
	"INSERT INTO $armorTable VALUES (0,'Leather Tunic',5040,10,1)",
	"INSERT INTO $armorTable VALUES (0,'Hooded Leather Cape',5850,11,1)",
	"INSERT INTO $armorTable VALUES (0,'Deerskin Leggings',6840,12,1)",
	"INSERT INTO $armorTable VALUES (0,'Deerskin Belt',8010,13,1)",
	"INSERT INTO $armorTable VALUES (0,'Deerskin Tunic',9000,14,1)",
	"INSERT INTO $armorTable VALUES (0,'Small Rawhide Shield',10350,15,1)",

	"INSERT INTO $weaponsTable VALUES (0,'Dull Bronze Sword',48,1,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Bronze Sword',225,2,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Crafted Bronze Sword',585,3,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Dull Iron Sword',990,4,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Iron Sword',1575,5,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Enchanted Sword',9000,14,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Crafted Iron Sword',2250,6,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Rusty Steel Sword',2790,7,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Dull Steel Sword',3420,8,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Crafted Steel Sword',4230,9,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Engraved Steel Sword',5040,10,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Steel Sword with Jeweled Hilt',5850,11,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Golden Hilted Sword',6840,12,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Platinum Hilted Sword',8010,13,2)",
	"INSERT INTO $weaponsTable VALUES (0,'Adept\\'s Sword',10350,15,2)",

	"INSERT INTO $armorTable VALUES (0,'Workboots',48,1,2)",
	"INSERT INTO $armorTable VALUES (0,'Overalls',225,2,2)",
	"INSERT INTO $armorTable VALUES (0,'Sturdy Leather Gloves',585,3,2)",
	"INSERT INTO $armorTable VALUES (0,'Sturdy Leather Bracers',990,4,2)",
	"INSERT INTO $armorTable VALUES (0,'Sturdy Leather Boots',1575,5,2)",
	"INSERT INTO $armorTable VALUES (0,'Sturdy Leather Helm',2250,6,2)",
	"INSERT INTO $armorTable VALUES (0,'Sturdy Leather Pants',2790,7,2)",
	"INSERT INTO $armorTable VALUES (0,'Sturdy Leather Tunic',3420,8,2)",
	"INSERT INTO $armorTable VALUES (0,'Sturdy Leather Cloak',4230,9,2)",
	"INSERT INTO $armorTable VALUES (0,'Woodsman\\'s Helm',5040,10,2)",
	"INSERT INTO $armorTable VALUES (0,'Woodsman\\'s Gauntlets',5850,11,2)",
	"INSERT INTO $armorTable VALUES (0,'Woodsman\\'s Bracers',6840,12,2)",
	"INSERT INTO $armorTable VALUES (0,'Woodsman\\'s Greaves',8010,13,2)",
	"INSERT INTO $armorTable VALUES (0,'Woodsman\\'s Tunic',9000,14,2)",
	"INSERT INTO $armorTable VALUES (0,'Woodsman\\'s Kite Shield',10350,15,2)",

	"INSERT INTO $weaponsTable VALUES (0,'Steel Longsword',48,1,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Etched Steel Longsword',585,3,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Polished Steel Longsword',225,2,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Balanced Steel Longsword',990,4,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Perfectly Balanced Steel Longsword',1575,5,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Engraved Steel Longsword',2250,6,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Longsword with Silver-plated Hilt',2790,7,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Longsword with Gold-plated Hilt',3420,8,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Longsword with Solid Gold Hilt',4230,9,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Longsword with Solid Platinum Hilt',5040,10,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Moonsilver Longsword',5850,11,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Autumngold Longsword',6840,12,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Elfsilver Longsword',8010,13,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Enchanted Longsword',9000,14,3)",
	"INSERT INTO $weaponsTable VALUES (0,'Wolfmaster\\'s Longsword',10350,15,3)",

	"INSERT INTO $armorTable VALUES (0,'Showercap and Towel',48,1,3)",
	"INSERT INTO $armorTable VALUES (0,'Bathrobe',225,2,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfskin Gloves',585,3,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfskin-lined Boots',990,4,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfskin Bracers',1575,5,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfskin Pants',2250,6,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfskin Tunic',2790,7,3)",
	"INSERT INTO $armorTable VALUES (0,'Hooded Wolfskin Cape',3420,8,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfmaster\\'s Bracers',4230,9,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfmaster\\'s Gauntlets',5040,10,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfmasters Helm',5850,11,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfmaster\\'s Leggings',6840,12,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfmaster\\'s Belted Jerkin',8010,13,3)",
	"INSERT INTO $armorTable VALUES (0,'Wolfhide Cape',9000,14,3)",
	"INSERT INTO $armorTable VALUES (0,'Shield of the Wolf Master',10350,15,3)",

	"INSERT INTO $weaponsTable VALUES (0,'Poorly Balanced Bastard Sword',48,1,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Tarnished Bastard Sword',225,2,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Iron Bastard Sword',585,3,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Steel Bastard Sword',990,4,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Balanced Steel Bastard Sword',1575,5,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Perfectly Balanced Bastard Sword',2250,6,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Rune-etched Bastard Sword',2790,7,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Bronze-inlay Bastard Sword',3420,8,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Silver-inlay Bastard Sword',4230,9,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Gold-inlay Bastard Sword',5040,10,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Nightsilver Bastard Sword',5850,11,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Morning-gold Bastard Sword',6840,12,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Truesplendor Bastard Sword',8010,13,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Enchanted Elfgold Bastard Sword',9000,14,4)",
	"INSERT INTO $weaponsTable VALUES (0,'Noble\\'s Bastard Sword',10350,15,4)",

	"INSERT INTO $armorTable VALUES (0,'Sweat Pants',48,1,4)",
	"INSERT INTO $armorTable VALUES (0,'Sweat Shirt',225,2,4)",
	"INSERT INTO $armorTable VALUES (0,'Studded Leather Helm',585,3,4)",
	"INSERT INTO $armorTable VALUES (0,'Studded Leather Gauntlets',990,4,4)",
	"INSERT INTO $armorTable VALUES (0,'Hardened Leather Boots',1575,5,4)",
	"INSERT INTO $armorTable VALUES (0,'Studded Leather Leggings',2250,6,4)",
	"INSERT INTO $armorTable VALUES (0,'Studded Leather Tunic',2790,7,4)",
	"INSERT INTO $armorTable VALUES (0,'Tanner\\'s Cape',3420,8,4)",
	"INSERT INTO $armorTable VALUES (0,'Rusty Chainmail Helm',4230,9,4)",
	"INSERT INTO $armorTable VALUES (0,'Rusty Chainmail Gauntlets',5040,10,4)",
	"INSERT INTO $armorTable VALUES (0,'Rusty Chainmail Bracers',5850,11,4)",
	"INSERT INTO $armorTable VALUES (0,'Rusty Chainmail Boots',6840,12,4)",
	"INSERT INTO $armorTable VALUES (0,'Rusty Chainmail Greaves',8010,13,4)",
	"INSERT INTO $armorTable VALUES (0,'Rusty Chainmail Tunic',9000,14,4)",
	"INSERT INTO $armorTable VALUES (0,'Large Iron Buckler',10350,15,4)",

	"INSERT INTO $weaponsTable VALUES (0,'Tarnished Iron Claymore',48,1,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Polished Iron Claymore',225,2,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Rusty Steel Claymore',585,3,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Steel Claymore',990,4,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Finely Crafted Steel Claymore',1575,5,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Scottish Broadsword',2250,6,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Viking War Sword',2790,7,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Barbarian\\'s Sword',3420,8,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Scottish Basket-Hilt Claymore',4230,9,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Agincourt Steel Sword',5040,10,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Celtic Combat Sword',5850,11,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Norseman\\'s Sword',6840,12,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Knight\\'s Sword',8010,13,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Heraldic Lion Claymore',9000,14,5)",
	"INSERT INTO $weaponsTable VALUES (0,'Dragon Soldier\\'s Claymore',10350,15,5)",

	"INSERT INTO $armorTable VALUES (0,'Bunny Slippers',48,1,5)",
	"INSERT INTO $armorTable VALUES (0,'Feety Pajamas',225,2,5)",
	"INSERT INTO $armorTable VALUES (0,'Comfortable Leather Undergarments',585,3,5)",
	"INSERT INTO $armorTable VALUES (0,'Heavy Chainmail Helm',990,4,5)",
	"INSERT INTO $armorTable VALUES (0,'Heavy Chainmail Gauntlets',1575,5,5)",
	"INSERT INTO $armorTable VALUES (0,'Heavy Chainmail Bracers',2250,6,5)",
	"INSERT INTO $armorTable VALUES (0,'Heavy Chainmail Boots',2790,7,5)",
	"INSERT INTO $armorTable VALUES (0,'Heavy Chainmail Greaves',3420,8,5)",
	"INSERT INTO $armorTable VALUES (0,'Heavy Chainmail Tunic',4230,9,5)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Soldier\\'s Bracers',5040,10,5)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Soldier\\'s Gauntlets',5850,11,5)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Soldier\\'s Boots',6840,12,5)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Soldier\\'s Greaves',8010,13,5)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Soldier\\'s Chestplate',9000,14,5)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Soldier\\'s Shield',10350,15,5)",

	"INSERT INTO $weaponsTable VALUES (0,'Two Broken Short Swords',48,1,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Two Short Swords',225,2,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Iron Scimitars',585,3,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Balanced Scimitars',990,4,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Tarnished Steel Scimitars',1575,5,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Rusty Steel Scimitars',2250,6,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Steel Scimitars',2790,7,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Bronze Hilted Steel Scimitars',3420,8,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Gold Hilted Steel Scimitars',4230,9,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Platinum Hilted Steel Scimitars',5040,10,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Crafted Adamantite Scimitars',5850,11,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Perfectly Crafted Adamantite Scimitars',6840,12,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Enchanted Scimitars',8010,13,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Drow Crafted Scimitars',9000,14,6)",
	"INSERT INTO $weaponsTable VALUES (0,'Unicorn Blood-Forged Scimitars',10350,15,6)",

	"INSERT INTO $armorTable VALUES (0,'Bluejeans',48,1,6)",
	"INSERT INTO $armorTable VALUES (0,'Flannel Shirt',225,2,6)",
	"INSERT INTO $armorTable VALUES (0,'Well Crafted Bronze Helm',585,3,6)",
	"INSERT INTO $armorTable VALUES (0,'Well Crafted Bronze Gauntlets',990,4,6)",
	"INSERT INTO $armorTable VALUES (0,'Well Crafted Bronze Bracers',1575,5,6)",
	"INSERT INTO $armorTable VALUES (0,'Well Crafted Bronze Boots',2250,6,6)",
	"INSERT INTO $armorTable VALUES (0,'Well Crafted Bronze Greaves',2790,7,6)",
	"INSERT INTO $armorTable VALUES (0,'Well Crafted Bronze Chestplate',3420,8,6)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Bronze Helm',4230,9,6)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Bronze Gauntlets',5040,10,6)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Bronze Bracers',5850,11,6)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Bronze Boots',6840,12,6)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Bronze Greaves',8010,13,6)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Bronze Chestplate',9000,14,6)",
	"INSERT INTO $armorTable VALUES (0,'Hooded Unicorn Skin Cloak',10350,15,6)",

	"INSERT INTO $weaponsTable VALUES (0,'Chipped Iron Axe',48,1,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Iron Axe',225,2,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Rusty Steel Axe',585,3,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Fine Steel Axe',990,4,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Lumberjack\\'s Axe',1575,5,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Low Quality Battle Axe',2250,6,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Medium Quality Battle Axe',2790,7,7)",
	"INSERT INTO $weaponsTable VALUES (0,'High Quality Battle Axe',3420,8,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Double Bladed Axe',4230,9,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Double Bladed Battle Axe',5040,10,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Gold Plated Battle Axe',5850,11,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Platinum Hilted Battle Axe',6840,12,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Enchanted Battle Axe',8010,13,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Dwarf Smith\\'s Battle Axe',9000,14,7)",
	"INSERT INTO $weaponsTable VALUES (0,'Dwarf Warrior\\'s Battle Axe',10350,15,7)",

	"INSERT INTO $armorTable VALUES (0,'Barrel',48,1,7)",
	"INSERT INTO $armorTable VALUES (0,'Lampshade',225,2,7)",
	"INSERT INTO $armorTable VALUES (0,'Perfectly Crafted Steel Helm',585,3,7)",
	"INSERT INTO $armorTable VALUES (0,'Perfectly Crafted Steel Gauntlets',990,4,7)",
	"INSERT INTO $armorTable VALUES (0,'Perfectly Crafted Steel Boots',1575,5,7)",
	"INSERT INTO $armorTable VALUES (0,'Perfectly Crafted Steel Bracers',2250,6,7)",
	"INSERT INTO $armorTable VALUES (0,'Perfectly Crafted Steel Greaves',2790,7,7)",
	"INSERT INTO $armorTable VALUES (0,'Perfectly Crafted Steel Chestplate',3420,8,7)",
	"INSERT INTO $armorTable VALUES (0,'Griffon-Feather Cloak',4230,9,7)",
	"INSERT INTO $armorTable VALUES (0,'Dwarven Chainmail Helm',5040,10,7)",
	"INSERT INTO $armorTable VALUES (0,'Dwarven Chainmail Gauntlets',5850,11,7)",
	"INSERT INTO $armorTable VALUES (0,'Dwarven Chainmail Boots',6840,12,7)",
	"INSERT INTO $armorTable VALUES (0,'Dwarven Chainmail Bracers',8010,13,7)",
	"INSERT INTO $armorTable VALUES (0,'Dwarven Chainmail Greaves',9000,14,7)",
	"INSERT INTO $armorTable VALUES (0,'Dwarven Chainmail Chestplate',10350,15,7)",

	"INSERT INTO $weaponsTable VALUES (0,'Broken Iron Mace',48,1,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Tarnished Iron Mace',225,2,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Polished Iron Mace',585,3,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Crafted Iron Mace',990,4,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Polished Steel Mace',1575,5,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Crafted Steel Mace',2250,6,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Poorly Balanced Double Mace',2790,7,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Well Balanced Double Mace',3420,8,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Battle Mace',4230,9,8)",
	"INSERT INTO $weaponsTable VALUES (0,'War Chieftain\\'s Battle Mace',5040,10,8)",
	"INSERT INTO $weaponsTable VALUES (0,'War Chieftain\\'s Morning Star',5850,11,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Adamantite Morning Star',6840,12,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Dwarf Crafted Morning Star',8010,13,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Dwarf Warlord\\'s Morning Star',9000,14,8)",
	"INSERT INTO $weaponsTable VALUES (0,'Enchanted Morning Star',10350,15,8)",

	"INSERT INTO $armorTable VALUES (0,'Fig Leaf',48,1,8)",
	"INSERT INTO $armorTable VALUES (0,'Kilt',225,2,8)",
	"INSERT INTO $armorTable VALUES (0,'Majestic Gold Helm',585,3,8)",
	"INSERT INTO $armorTable VALUES (0,'Majestic Gold Gauntlets',990,4,8)",
	"INSERT INTO $armorTable VALUES (0,'Majestic Gold Boots',1575,5,8)",
	"INSERT INTO $armorTable VALUES (0,'Bracers',2250,6,8)",
	"INSERT INTO $armorTable VALUES (0,'Majestic Gold Greaves',2790,7,8)",
	"INSERT INTO $armorTable VALUES (0,'Majestic Gold Chestplate',3420,8,8)",
	"INSERT INTO $armorTable VALUES (0,'Majestic Gold Shield',4230,9,8)",
	"INSERT INTO $armorTable VALUES (0,'Gold-Threaded Cloak',5040,10,8)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Ruby Ring',5850,11,8)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Sapphire Ring',6840,12,8)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Jade Ring',8010,13,8)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Amethyst Ring',9000,14,8)",
	"INSERT INTO $armorTable VALUES (0,'Enchanted Diamond Ring',10350,15,8)",

	"INSERT INTO $weaponsTable VALUES (0,'Boot Knife',48,1,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Target Knife',225,2,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Blackjack',585,3,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Throwing Star',990,4,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Hira-Shuriken',1575,5,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Throwing Spike',2250,6,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Atlatl',2790,7,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Qilamitautit Bolo',3420,8,9)",
	"INSERT INTO $weaponsTable VALUES (0,'War Quoait',4230,9,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Cha Kran',5040,10,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Fei Piau',5850,11,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Jen Piau',6840,12,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Gau dim Piau',8010,13,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Enchanted Throwing Axe',9000,14,9)",
	"INSERT INTO $weaponsTable VALUES (0,'Teksolo\\'s Ninja Stars',10350,15,9)",

	"INSERT INTO $armorTable VALUES (0,'Button',48,1,9)",
	"INSERT INTO $armorTable VALUES (0,'Elven Silk Nightclothes',225,2,9)",
	"INSERT INTO $armorTable VALUES (0,'Elven Silk Gloves',585,3,9)",
	"INSERT INTO $armorTable VALUES (0,'Elven Silk Slippers',990,4,9)",
	"INSERT INTO $armorTable VALUES (0,'Elven Silk Wristband',1575,5,9)",
	"INSERT INTO $armorTable VALUES (0,'Leggings',2250,6,9)",
	"INSERT INTO $armorTable VALUES (0,'Elven Silk Tunic',2790,7,9)",
	"INSERT INTO $armorTable VALUES (0,'Elven Silk Cloak',3420,8,9)",
	"INSERT INTO $armorTable VALUES (0,'Ring of Night',4230,9,9)",
	"INSERT INTO $armorTable VALUES (0,'Ring of Day',5040,10,9)",
	"INSERT INTO $armorTable VALUES (0,'Ring of Solitude',5850,11,9)",
	"INSERT INTO $armorTable VALUES (0,'Ring of Peace',6840,12,9)",
	"INSERT INTO $armorTable VALUES (0,'Ring of Courage',8010,13,9)",
	"INSERT INTO $armorTable VALUES (0,'Ring of Virtue',9000,14,9)",
	"INSERT INTO $armorTable VALUES (0,'Ring of Life',10350,15,9)",

	"INSERT INTO $weaponsTable VALUES (0,'Farmer\\'s Bow & Wooden Arrows',48,1,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Farmer\\'s Bow & Stone Tipped Arrows',225,2,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Farmer\\'s Bow & Steel Tipped Arrows',585,3,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Hunter\\'s Bow & Wooden Arrows',990,4,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Hunter\\'s Bow & Stone Tipped Arrows',1575,5,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Hunter\\'s Bow & Steel Tipped Arrows',2250,6,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Ranger\\'s Bow & Wooden Arrows',2790,7,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Ranger\\'s Bow & Stone Tipped Arrows',3420,8,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Ranger\\'s Bow & Steel Tipped Arrows',4230,9,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Longbow',5040,10,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Crossbow',5850,11,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Elvish Longbow',6840,12,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Elvish Longbow & Flame Tipped Arrows',8010,13,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Elvish Longbow & Enchanted Arrows',9000,14,10)",
	"INSERT INTO $weaponsTable VALUES (0,'Longbow of the Elf King',10350,15,10)",

	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Hooded Cloak',5040,10,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Chestplate',4230,9,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Greaves',3420,8,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Boots',2790,7,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Gorget',2250,6,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Bracers',1575,5,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Gauntlets',990,4,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Helm',585,3,10)",
	"INSERT INTO $armorTable VALUES (0,'Platform Shoes',225,2,10)",
	"INSERT INTO $armorTable VALUES (0,'Leisure Suit',48,1,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus Feather Pendant',5850,11,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus Feather Belt',6840,12,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Emblazoned Shield',8010,13,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Emblazoned Ring',9000,14,10)",
	"INSERT INTO $armorTable VALUES (0,'Pegasus\\' Emblazoned Crown',10350,15,10)",

	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Long Sword',225,2,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Short Sword',48,1,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Bastard Sword',585,3,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Scimitars',990,4,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Battle Axe',1575,5,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Throwing Hammer',2250,6,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Morning Star',2790,7,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Compound Bow',3420,8,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Rapier',4230,9,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Sabre',5040,10,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Light Sabre',5850,11,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Wakizashi',6840,12,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s 2-Handed War Sword',8010,13,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s 2-handed War Axe',9000,14,11)",
	"INSERT INTO $weaponsTable VALUES (0,'MightyE\\'s Claymore',10350,15,11)",

	"INSERT INTO $armorTable VALUES (0,'New Clothes',48,1,11)",
	"INSERT INTO $armorTable VALUES (0,'Chicken Suit',225,2,11)",
	"INSERT INTO $armorTable VALUES (0,'Gauntlets of Grace',585,3,11)",
	"INSERT INTO $armorTable VALUES (0,'Bracer of Beauty',990,4,11)",
	"INSERT INTO $armorTable VALUES (0,'Helm of Health',1575,5,11)",
	"INSERT INTO $armorTable VALUES (0,'Greaves of Good Fortune',2250,6,11)",
	"INSERT INTO $armorTable VALUES (0,'Boots of Bravery',2790,7,11)",
	"INSERT INTO $armorTable VALUES (0,'Tunic of Tolerance',3420,8,11)",
	"INSERT INTO $armorTable VALUES (0,'Cloak of Confidence',4230,9,11)",
	"INSERT INTO $armorTable VALUES (0,'Ring of Righteousness',5040,10,11)",
	"INSERT INTO $armorTable VALUES (0,'Necklace of Narcissism',5850,11,11)",
	"INSERT INTO $armorTable VALUES (0,'Pendant of Power',6840,12,11)",
	"INSERT INTO $armorTable VALUES (0,'Breastplate of Benevolence',8010,13,11)",
	"INSERT INTO $armorTable VALUES (0,'Shield of Superiority',9000,14,11)",
	"INSERT INTO $armorTable VALUES (0,'Scepter of Strength',10350,15,11)",

	"INSERT INTO $weaponsTable VALUES (0,'Spell of Fire',48,1,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Earthquake',225,2,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Flood',585,3,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Hurricane',990,4,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Mind Control',1575,5,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Lightning',2250,6,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Weakness',2790,7,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Fear',3420,8,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Poison',4230,9,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Spirit Possession',5040,10,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Despair',5850,11,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Bat Summoning',6840,12,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Wolf Summoning',8010,13,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Unicorn Summoning',9000,14,12)",
	"INSERT INTO $weaponsTable VALUES (0,'Spell of Dragon Summoning',10350,15,12)",

	"INSERT INTO $armorTable VALUES (0,'Dragon Skin Leather Helm',48,1,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Skin Leather Gauntlets',225,2,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Skin Leather Boots',585,3,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Skin Leather Bracers',990,4,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Skin Leather Leggings',1575,5,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Skin Leather Tunic',2250,6,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Skin Leather Cloak',2790,7,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Scale Helm',3420,8,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Scale Gauntlets',4230,9,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Scale Boots',5040,10,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Scale Bracers',5850,11,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Scale Greaves',6840,12,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Scale Chestplate',8010,13,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Scale Cloak',9000,14,12)",
	"INSERT INTO $armorTable VALUES (0,'Dragon Talon Shield',10350,15,12)",
];