<?php

return [
	"REPLACE INTO `cronjob` (`name`, `command`, `schedule`, `mailer`, `maxRuntime`, `smtpHost`, `smtpPort`, `smtpUsername`, `smtpPassword`, `smtpSender`, `smtpSenderName`, `smtpSecurity`, `runAs`, `environment`, `runOnHost`, `output`, `dateFormat`, `enabled`, `haltDir`, `debug`) VALUES ('lotgdCacheoptimize', 'cronjob/cacheoptimize', '* * */2 * *', 'sendmail', NULL, NULL, NULL, NULL, NULL, 'jobby@localhost', 'Jobby', NULL, NULL, NULL, NULL, NULL, 'Y-m-d H:i:s', 1, NULL, 0);",
    "REPLACE INTO `cronjob` (`name`, `command`, `schedule`, `mailer`, `maxRuntime`, `smtpHost`, `smtpPort`, `smtpUsername`, `smtpPassword`, `smtpSender`, `smtpSenderName`, `smtpSecurity`, `runAs`, `environment`, `runOnHost`, `output`, `dateFormat`, `enabled`, `haltDir`, `debug`) VALUES ('lotgdCharcleanup', 'cronjob/charcleanup', '*/30 * * * *', 'sendmail', NULL, NULL, NULL, NULL, NULL, 'jobby@localhost', 'Jobby', NULL, NULL, NULL, NULL, NULL, 'Y-m-d H:i:s', 1, NULL, 0);",
    "REPLACE INTO `cronjob` (`name`, `command`, `schedule`, `mailer`, `maxRuntime`, `smtpHost`, `smtpPort`, `smtpUsername`, `smtpPassword`, `smtpSender`, `smtpSenderName`, `smtpSecurity`, `runAs`, `environment`, `runOnHost`, `output`, `dateFormat`, `enabled`, `haltDir`, `debug`) VALUES ('lotgdCommentcleanup', 'cronjob/commentcleanup', '* * */7 * *', 'sendmail', NULL, NULL, NULL, NULL, NULL, 'jobby@localhost', 'Jobby', NULL, NULL, NULL, NULL, NULL, 'Y-m-d H:i:s', 1, NULL, 0);",
    "REPLACE INTO `cronjob` (`name`, `command`, `schedule`, `mailer`, `maxRuntime`, `smtpHost`, `smtpPort`, `smtpUsername`, `smtpPassword`, `smtpSender`, `smtpSenderName`, `smtpSecurity`, `runAs`, `environment`, `runOnHost`, `output`, `dateFormat`, `enabled`, `haltDir`, `debug`) VALUES ('lotgdDbcleanup', 'cronjob/dbcleanup', '0 4 * * *', 'sendmail', NULL, NULL, NULL, NULL, NULL, 'jobby@localhost', 'Jobby', NULL, NULL, NULL, NULL, NULL, 'Y-m-d H:i:s', 1, NULL, 0);",
    "REPLACE INTO `cronjob` (`name`, `command`, `schedule`, `mailer`, `maxRuntime`, `smtpHost`, `smtpPort`, `smtpUsername`, `smtpPassword`, `smtpSender`, `smtpSenderName`, `smtpSecurity`, `runAs`, `environment`, `runOnHost`, `output`, `dateFormat`, `enabled`, `haltDir`, `debug`) VALUES ('lotgdNewday', 'cronjob/newday', '0 0,6,12,18 * * *', 'sendmail', NULL, NULL, NULL, NULL, NULL, 'jobby@localhost', 'Jobby', NULL, NULL, NULL, NULL, NULL, 'Y-m-d H:i:s', 1, NULL, 0);"
];
