doctrine:
    orm:
        mappings:
            Lotgd\Bundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle'
                prefix: Lotgd\Bundle\Entity


