# Main WebSite
<VirtualHost *:443>
	ServerName localhost
	ServeAlias www.localhost
	#UseCanonicalName Off

	ErrorLog /usr/local/apache2/logs/error-ssl.log
	CustomLog /usr/local/apache2/logs/access-ssl.log combined

	Include conf/x/common.conf
	Include conf/x/prod-certs.conf

	<IfModule mod_rewrite.c>
		RewriteEngine On
		# Add the www in front if they have not been added
    RewriteCond %{HTTP_HOST} !^www\. [NC]
    RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]
	</IfModule>
</VirtualHost>

# Administration panel
<VirtualHost *:443>
	ServerName admin.localhost
	#UseCanonicalName Off

	SetEnv APP_ID admin

	ErrorLog /usr/local/apache2/logs/admin-error-ssl.log
	CustomLog /usr/local/apache2/logs/admin-access-ssl.log combined

	Include conf/x/common.conf
	Include conf/x/prod-certs.conf
</VirtualHost>

# Api
<VirtualHost *:443>
	ServerName api.localhost
	#UseCanonicalName Off

	SetEnv APP_ID api

	ErrorLog /usr/local/apache2/logs/api-error-ssl.log
	CustomLog /usr/local/apache2/logs/api-access-ssl.log combined

	Include conf/x/common.conf
	Include conf/x/dev-certs.conf
</VirtualHost>
