monolog:
    handlers:
        main:
            type: rotating_file
            action_level: error
            handler: nested
            # excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            channels: ["!security", '!cache', '!http_client']
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        security:
            # log all messages (since debug is the lowest level)
            level: debug
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_security.log'
            channels: [security]
        cache:
            # log all messages (since debug is the lowest level)
            level: debug
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_cache.log'
            channels: [cache]
        http_client:
            # log all messages (since debug is the lowest level)
            level: debug
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_http_client.log'
            channels: [http_client]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!security", '!cache', '!http_client']
