# # Redirect old files to new routes.
# # # # # # # # # # # # # # # # # # #

# create.php?op=forgot
lotgd_core_legacy_redirect_create_forgot:
    path: /create.php
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    condition: "request.query.get('op') == 'forgot'"
    defaults:
        route: lotgd_user_forgot_password_request
        permanent: true
        keepQueryParams: false
        keepRequestMethod: true

# create.php
lotgd_core_legacy_redirect_create:
    path: /create.php
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: lotgd_user_register
        permanent: true
        keepQueryParams: false
        keepRequestMethod: true
