<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class                    => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class     => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class                              => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class                => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class                        => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class                            => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class                            => ['dev' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class                     => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class         => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class                      => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class                        => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class                   => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class        => ['all' => true],
    Cron\CronBundle\CronCronBundle::class                                    => ['all' => true],
    Bukashk0zzz\FilterBundle\Bukashk0zzzFilterBundle::class                  => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class                     => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class                               => ['all' => true],
    Sonata\Doctrine\Bridge\Symfony\SonataDoctrineSymfonyBundle::class        => ['all' => true],
    Sonata\Form\Bridge\Symfony\SonataFormBundle::class                       => ['all' => true],
    Sonata\BlockBundle\SonataBlockBundle::class                              => ['all' => true],
    Sonata\Twig\Bridge\Symfony\SonataTwigSymfonyBundle::class                => ['all' => true],
    Sonata\Exporter\Bridge\Symfony\SonataExporterSymfonyBundle::class        => ['all' => true],
    Sonata\AdminBundle\SonataAdminBundle::class                              => ['all' => true],
    Sonata\TranslationBundle\SonataTranslationBundle::class                  => ['all' => true],
    Sonata\IntlBundle\SonataIntlBundle::class                                => ['all' => true],
    Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle::class        => ['all' => true],
    Sylius\Bundle\ThemeBundle\SyliusThemeBundle::class                       => ['all' => true],
    SymfonyCasts\Bundle\VerifyEmail\SymfonyCastsVerifyEmailBundle::class     => ['all' => true],
    SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class             => ['dev' => true, 'test' => true],
    Lotgd\Bundle\CoreBundle\LotgdCoreBundle::class                           => ['all' => true],
    Lotgd\Bundle\CreatureBundle\LotgdCreatureBundle::class                   => ['all' => true],
    Lotgd\Bundle\AdminBundle\LotgdAdminBundle::class                         => ['all' => true],
    Lotgd\Bundle\SettingsBundle\LotgdSettingsBundle::class                   => ['all' => true],
    Lotgd\Bundle\UiBundle\LotgdUiBundle::class                               => ['all' => true],
    Lotgd\Bundle\UserBundle\LotgdUserBundle::class                           => ['all' => true],
];
