<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class                    => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class     => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class                              => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class                => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class                        => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class                            => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class                            => ['dev' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class                     => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class         => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class                      => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class                        => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class                   => ['all' => true],
    Sylius\Bundle\ThemeBundle\SyliusThemeBundle::class                       => ['all' => true],
    Bukashk0zzz\FilterBundle\Bukashk0zzzFilterBundle::class                  => ['all' => true],
    Sonata\Doctrine\Bridge\Symfony\SonataDoctrineSymfonyBundle::class        => ['all' => true],
    Sonata\Twig\Bridge\Symfony\SonataTwigSymfonyBundle::class                => ['all' => true],
    Sonata\Form\Bridge\Symfony\SonataFormBundle::class                       => ['all' => true],
    Sonata\BlockBundle\SonataBlockBundle::class                              => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class        => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class                               => ['all' => true],
    Sonata\Exporter\Bridge\Symfony\SonataExporterSymfonyBundle::class        => ['all' => true],
    Sonata\AdminBundle\SonataAdminBundle::class                              => ['all' => true],
    Cron\CronBundle\CronCronBundle::class                                    => ['all' => true],
    Jaxon\AjaxBundle\JaxonAjaxBundle::class                                  => ['all' => true],
    SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
];
