parameters:
    jaxon:
        app:
            directories:
                '%kernel.project_dir%/jaxon/App':
                    namespace: \Jaxon\App
                    # separator: '' # '.' or '_'
                    # protected: []

        lib:
            core:
                language: '%kernel.default_locale%'
                encoding: "UTF-8"
                request:
                    uri: "/jaxon"
                prefix:
                    class: ""
                debug:
                    on: false
                    verbose: false
                error:
                    handle: false
                js:
                    lib:
                    app:
                    export: false
                    minify: false

            dialogs:
                default:
                    message: toastr
                    modal: semantic
                classes:
                    semantic: Lotgd\Core\Jaxon\Library\Semantic\Modal
                toastr:
                    options:
                        progressBar: true
                        newestOnTop: false
                        closeButton: true
                        preventDuplicates: true
                        timeOut: 30000
                        extendedTimeOut: 15000
