<?php
$info = array(
		'name'=>'Equipment Shop',
		'version'=>'3.813',
		'author'=>'Eth, enhanced by `&W`7hite `&K`7night',
		'category'=>'Equipment Shop',
		'download'=>'http://dragonprime.net/index.php?module=Downloads;sa=dlview;id=262',
		'settings'=>array(
			'Equipment Shop - Main,title',
			'dkreq'=>'DK\'s needed to visit shop?,int|1',
			'shopname'=>'What\'s the name of the shop?|Ye Olde Equipment Shoppe',
			'shopkeepname'=>'What\'s the name of the shopkeep?|Illyria',
			'Shop is available to everyone or to donators only. Take your pick.,note',
			'shopappear'=>'Where is shop available?,enum,0,Village,1,Hunter\'s Lodge',
			'shoploc'=>'What town does the shop appear in?,location|'.getsetting( 'villagename', LOCATION_FIELDS ),
			'shopall'=>'OR Do you want the shop to appear everywhere?,bool|0',
			'restoreAll'=>'Restore item buffs after DK\'s for everybody?,bool|'.true,
			'Item enhancements will be re-added after each DK only if individual preferences allow (which they do by default).,note',
			'Defaults,title',
			'The name of armor and weapon that a player gets once a corresponding magical item is sold. Empty custom armor/weapon field(s) will make the module read global defaults from the database.,note',
			'def_weapon'=>'Custom level 0 weapon name ',
			'def_armor'=>'Custom level 0 armor name ',
			'Dragon Kill,title',
			'Weapons and armor are lost automatically after a dragon kill (so no option for them exists).,note',
			'losechance'=>'Chance to lose individual item?,range,0,100,1|20',
			'losering'=>'Lose ring after a DK?,bool|0',
			'loseamulet'=>'Lose amulet after a DK?,bool|0',
			'losehelm'=>'Lose helm after a DK?,bool|0',
			'losecloak'=>'Lose cloak after a DK?,bool|0',
			'loseglove'=>'Lose gloves after a DK?,bool|0',
			'loseboot'=>'Lose boots after a DK?,bool|0',
			'losemisc'=>'Lose misc item after a DK?,bool|0',
			'dkreaddrare'=>'Should rare items lost after a DK be added back to store inventory?,bool|'.false,
			'Donation Settings,title',
			'Only useful if you have this enabled for donators only.,note',
			'pointsreq'=>'Donation points needed to buy pass to shop?,int|100',
			'Shop Description,title',
			'Enter a custom description for your shop here. Players see this when they first enter.,note',
			'This is completely optional; a default message will be displayed if this field is empty.,note',
			'shopdesc'=>',textarea',
			'Sell Options,title',
			'displaydesc'=>'Display short item description?,bool|1',
			'showstats'=>'Display item stats in preview?,bool|0',
			'shownum'=>'How many items to show per page?,int|15',
			'givegift'=>'Allow gift-giving?,bool|1',
			'giftholdlimit'=>'What level must players reach to be able to receive gifts? ,range,1,15,1|1',
			'The gift will be available immediately if the selected level is 1.,note',
			'discount'=>'Give discount based on charm?,bool|0',
			'discountnum'=>'Discount modifier,int|400',
			'The higher the number - the lower the discount. 400 = 25% discount at 100 charm.,note'
		),
		'prefs'=>array(	
			'Equipment Shop - Misc Settings,title',
			'pass'=>'Have a pass?,bool|0',
			'res'=>'User resurrections,int|0',
			'favor'=>'Wearing favor item?,bool|0',
			'favoradd'=>'Total favor granted?,int|0',
			'turnadd'=>'Total turns granted?,int|0',
			'Item Settings,title',
			'amulet'=>'Own an amulet?,bool|0',
			'amuletid'=>'Amulet ID?,int|0',
			'amuletname'=>'Name of Amulet?|None',
			'ringid'=>'Ring ID?,int|0',
			'ring'=>'Own a Ring?,bool|0',
			'ringname'=>'Name of Ring?|None',
			'weapon'=>'Own a weapon?,bool|0',
			'weaponid'=>'Weapon ID?,int|0',
			'weaponname'=>'Name of Weapon?|None',
			'armor'=>'Own magic armor?,bool|0',
			'armorid'=>'Armor ID?,int|0',
			'armorname'=>'Name of Armor?|None',
			'cloak'=>'Own Cloak?,bool|0',
			'cloakid'=>'Cloak ID?,int|0',
			'cloakname'=>'Name of Cloak?|None',
			'helm'=>'Own Helm?,bool|0',
			'helmid'=>'Helm ID?,int|0',
			'helmname'=>'Name of Helm?|None',
			'glove'=>'Own Gloves?,bool|0',
			'gloveid'=>'Gloves ID?,int|0',
			'glovename'=>'Name of Gloves?|None',
			'boots'=>'Own Boots?,bool|0',
			'bootid'=>'Boots ID?,int|0',
			'bootname'=>'Name of Boots?|None',
			'misc'=>'Own Misc Item?,bool|0',
			'miscid'=>'Misc Item ID?,int|0',
			'miscname'=>'Name of Misc Item?|None',
			'restoreIndiv'=>'Restore item buffs after DK\'s?,enum,1,Yes,0,Use global setting,2,No|0',
			'applyall'=>'Apply all item enhancements on save?`n`i(Applying adds to previous values. Irreversible.)`i,bool|'.false,
			'Gift Settings,title',
			'gifted'=>'Been gifted yet?,bool|0',
			'giftid'=>'ID of gifted item,int|0',
			'giftcat'=>'Category of gifted item,int|0',
			'Equipment Display,title',
			'user_display'=>'Display Equipment Info?,bool|1'
		)
	);
?>