# Headers
Header set X-XSS-Protection 1
Header set X-Frame-Options "sameorigin"
Header set Referrer-Policy no-referrer strict-origin strict-origin same-origin-when-cross-origin
Header always set X-Content-Type-Options "nosniff"

Header set Cross-Origin-Opener-Policy: same-origin-allow-popups
Header set Cross-Origin-Resource-Policy: same-origin
