<?php
	$row = array(
		"id"=>"",
    "name"=>"",
    "levelreq"=>"",
    "type"=>"",
    "startmsg"=>"",
    "effectmsg"=>"",
    "effectnodmgmsg"=>"",
    "effectfailmsg"=>"",
    "roundmsg"=>"",
		"wearoff"=>"",
		"manacost"=>"",
		"rounds"=>"1",
    "minioncount"=>"",
    "mingoodguydamage"=>"0",
    "maxgoodguydamage"=>"0",
    "minbadguydamage"=>"0",
    "maxbadguydamage"=>"0",
    "badguydmgmod"=>"1",
    "badguyatkmod"=>"1",
    "badguydefmod"=>"1",
    "atkmod"=>"1",
    "defmod"=>"1",
		"damageshield"=>"",    
    "lifetap"=>"",
    "regen"=>"",
	);
	rawoutput("<form action='runmodule.php?module=skilleditor&op=editor&what=save&id=$id' method='POST'>");
	addnav("","runmodule.php?module=skilleditor&op=editor&what=save&id=$id");
	require_once("lib/showform.php");
	showform($skillarray,$row);
	rawoutput("</form>");
?>
