doctrine:
    orm:
        mappings:
            LotgdSettingsBundle:
                is_bundle: true
                type: annotation
                prefix: 'Lotgd\Bundle\SettingsBundle\Entity'
                alias: LotgdSettings
