name: LoTGD Test Suite

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    tags-ignore:
      - dependencies
  push:
    branches:
      - '7.1'

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.4' ]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: ${{ (matrix.php == '7.4') && '0' || '1' }}

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: Run test suite on PHP ${{ matrix.php }}
        run: ./vendor/bin/phpunit

      - name: Fix paths for Sonar
        if: matrix.php == '7.4'
        working-directory: ./build/reports/
        run: sed -i 's/\/home\/runner\/work\/common-bundle\/common-bundle\//\/github\/workspace\//g' phpunit.coverage.xml

      - name: SonarCloud Scan
        if: matrix.php == '7.4'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}