name: LoTGD Test Suite

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    tags-ignore: [ dependencies, documentation, meta, 'docker configuration', 'deployer configuration' ]
  push:
    paths-ignore:
      - '.deployer/**'
      - '.docker/**'
      - 'migrations/**'
      - '**/docs/**'
      - '**/Writerside/**'
      - '**/README.md'
      - '**/COMMANDS.md'
      - '**/TIPS.md'
      - '**/TODO.md'
      - '**/LICENSE'
      - rector.php
      - .editorconfig
      - .gitignore
      - compose.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: [ '7.4' ]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: ${{ (matrix.php == '7.4') && '0' || '1' }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: Run test suite on PHP ${{ matrix.php }}
        run: ./vendor/bin/phpunit --exclude ignore

      - name: SonarCloud Scan
        if: matrix.php == '7.4'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}